// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iiemr5oFHV2rT4bVfeUAHQ
// Component: KM10DMtg68199a
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import HeroSection2 from "../../HeroSection2"; // plasmic-import: 3XNBWGhrQYp/component
import Button from "../../Button"; // plasmic-import: QaipWgLIw8/component
import Divider from "../../Divider"; // plasmic-import: 41plLt4nRZ/component
import Textinput from "../../Textinput"; // plasmic-import: Ds50KhWxRf/component
import Navigation from "../../Navigation"; // plasmic-import: QL_hAqdWKc/component
import ValuesSection3 from "../../ValuesSection3"; // plasmic-import: MA4bVcmaSsw/component
import Valueprop from "../../Valueprop"; // plasmic-import: YnVQB3eyyN/component
import ValuesSection2Dark from "../../ValuesSection2Dark"; // plasmic-import: e-zwD-1wQRG/component
import PricingSection3 from "../../PricingSection3"; // plasmic-import: 2eOBL4VENE9/component
import ShopBanners from "../../ShopBanners"; // plasmic-import: cmWRjF4k6DZ/component
import Banner from "../../Banner"; // plasmic-import: d6LyhpMUyX/component
import LogoCloudSection2 from "../../LogoCloudSection2"; // plasmic-import: IaLiG14Rft/component
import TestimonialsSection1 from "../../TestimonialsSection1"; // plasmic-import: CkgoUikSrtH/component
import Testimonial from "../../Testimonial"; // plasmic-import: 1MFPRU1oT6/component
import CallToActionSection1 from "../../CallToActionSection1"; // plasmic-import: qZnnGE7HkYG/component
import { useScreenVariants } from "../landing_kit/PlasmicGlobalVariant__Screen"; // plasmic-import: K7Rqgqmh9OYf/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_page_starter.module.css"; // plasmic-import: iiemr5oFHV2rT4bVfeUAHQ/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: KM10DMtg68199a/css
import Icon6Icon from "../landing_kit/icons/PlasmicIcon__Icon6"; // plasmic-import: Po8b91h4Ib/icon
import Icon5Icon from "../landing_kit/icons/PlasmicIcon__Icon5"; // plasmic-import: F3iKvVwbFc/icon
import Icon14Icon from "../landing_kit/icons/PlasmicIcon__Icon14"; // plasmic-import: h9S1yezhrN/icon
import image13XpI2S7PCl2 from "../landing_kit/images/image13.svg"; // plasmic-import: XpI2S7pCl2/picture

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <HeroSection2
            data-plasmic-name={"heroSection2"}
            data-plasmic-override={overrides.heroSection2}
            className={classNames("__wab_instance", sty.heroSection2)}
            foreground={
              <React.Fragment>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__qwNk)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__hLtk)}
                  >
                    <div className={classNames(defaultcss.all, sty.box__lx6NY)}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__t9Qb
                        )}
                      >
                        {"Updated!"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box___2R5Hy
                      )}
                    >
                      <span>
                        <React.Fragment>{"Designs that "}</React.Fragment>
                        <span style={{ textDecoration: "underline" }}>
                          {"adapt"}
                        </span>
                      </span>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__pD5TW
                      )}
                    >
                      {
                        "Orci dui condimentum rutrum laoreet hac purus porta sem sem a vivamus a posuere vel molestie."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__evOdk)}
                  >
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__rQdex
                      )}
                      darkGray={"darkGray"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__oDdB
                          )}
                        >
                          {"Start now ->"}
                        </div>
                      }
                    />

                    <Button
                      bgDifference={"bgDifference"}
                      className={classNames(
                        "__wab_instance",
                        sty.button__vwPNv
                      )}
                      darkGray={"darkGray"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__okhPe
                          )}
                        >
                          {"Learn more…"}
                        </div>
                      }
                    />
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__vBkVa)}
                >
                  <div className={classNames(defaultcss.all, sty.box__zYcWd)}>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__vd4Oa)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__onEBk
                        )}
                      >
                        {"Sign up with"}
                      </div>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box___38Zh)}
                      >
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__buVvR
                          )}
                          ouline={"ouline"}
                          slot={"Apple"}
                          startIcon={"startIcon"}
                        />

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__uxULx
                          )}
                          ouline={"ouline"}
                          slot={"Google"}
                          startIcon={"startIcon"}
                        >
                          <Icon6Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__py790
                            )}
                            role={"img"}
                          />
                        </Button>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__dhQ4)}
                      >
                        <Divider
                          className={classNames(
                            "__wab_instance",
                            sty.divider__wfFep
                          )}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__dlXRl
                          )}
                        >
                          {"Or"}
                        </div>

                        <Divider
                          className={classNames(
                            "__wab_instance",
                            sty.divider__boahk
                          )}
                        />
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box___8DxTz)}
                      >
                        <Textinput
                          className={classNames(
                            "__wab_instance",
                            sty.textinput___3DHju
                          )}
                        />

                        <Textinput
                          className={classNames(
                            "__wab_instance",
                            sty.textinput__wtIN
                          )}
                        />

                        <Textinput
                          className={classNames(
                            "__wab_instance",
                            sty.textinput___9DvIh
                          )}
                        />
                      </p.Stack>

                      <Button
                        children2={
                          <Icon5Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__vv2Qi
                            )}
                            role={"img"}
                          />
                        }
                        className={classNames(
                          "__wab_instance",
                          sty.button__tc7He
                        )}
                        colors={"indigo"}
                        slot={"Start your account"}
                      />
                    </p.Stack>

                    <Divider
                      className={classNames(
                        "__wab_instance",
                        sty.divider__vvvku
                      )}
                    />

                    <div className={classNames(defaultcss.all, sty.box__mos6H)}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__as9W5
                        )}
                      >
                        {
                          "A cras sagittis odio vestibulum pulvinar a eget hendrerit id vestibulum a leo sociosqu dictumst dictumst natoque magnis parturient."
                        }
                      </div>
                    </div>
                  </div>
                </p.Stack>
              </React.Fragment>
            }
          >
            <Navigation
              data-plasmic-name={"navigation"}
              data-plasmic-override={overrides.navigation}
              className={classNames("__wab_instance", sty.navigation)}
              hideCta={"hideCta"}
              slot={
                <React.Fragment>
                  <Button
                    className={classNames("__wab_instance", sty.button__j1SlO)}
                    link={"#services"}
                    navLink={"navLink"}
                    slot={"Services"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button___9QY2X)}
                    link={"#features"}
                    navLink={"navLink"}
                    slot={"Features"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__r7XyC)}
                    link={"#pricing"}
                    navLink={"navLink"}
                    slot={"Pricing"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__eVqrl)}
                    link={"#testimonials"}
                    navLink={"navLink"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__uR8Nx
                        )}
                      >
                        {"Testimonials"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__amdd9)}
                    navLink={"navLink"}
                    slot={"Log in"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__hUh7C)}
                    darkGray={"darkGray"}
                    slot={"Sign up"}
                  />
                </React.Fragment>
              }
            >
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___3UCh9)}
                role={"img"}
                src={image13XpI2S7PCl2}
              />
            </Navigation>
          </HeroSection2>

          <div
            className={classNames(defaultcss.all, sty.box__lwiYu)}
            id={"services"}
          >
            <ValuesSection3
              data-plasmic-name={"valuesSection3"}
              data-plasmic-override={overrides.valuesSection3}
              foreground={
                <React.Fragment>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__eyaPl)}
                  >
                    <div
                      className={classNames(defaultcss.all, sty.box___1JrBn)}
                    >
                      <h2
                        data-plasmic-name={"h2"}
                        data-plasmic-override={overrides.h2}
                        className={classNames(
                          defaultcss.h2,
                          defaultcss.__wab_text,
                          sty.h2
                        )}
                      >
                        {"Proposing values"}
                      </h2>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box___9216B
                      )}
                    >
                      {
                        "Consectetur a adipiscing sagittis sed proin libero himenaeos ornare adipiscing suscipit leo vestibulum facilisi consequat nisi nisi adipiscing habitant facilisis suspendisse hac integer eget quam facilisis sem placerat fames."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__mfu9A)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__xxX6T)}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__z812F
                        )}
                        flat={"flat"}
                        slot={
                          "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___307O
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Powerful"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__cpIiy
                        )}
                        flat={"flat"}
                        slot={
                          "Consequat scelerisque a eros taciti nisl a sodales."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__cnO2V
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Faster"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__otSnB
                        )}
                        flat={"flat"}
                        slot={"At ut condimentum amet adipiscing ac diam a."}
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__n3HKy
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Best and brightest"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__fxf5F
                        )}
                        flat={"flat"}
                        slot={
                          "Donec purus nec vestibulum volutpat vivamus vulputate suspendisse."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__xKdXh
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__ztG32
                          )}
                        >
                          {"Dynamic range"}
                        </div>
                      </Valueprop>
                    </p.Stack>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__q44Zs)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__aQoOy)}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__cSdEq
                        )}
                        flat={"flat"}
                        slot={
                          "Commodo pretium himenaeos nisi potenti ad in ante."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__xTkgO
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__uiPlY
                          )}
                        >
                          {"Portable"}
                        </div>
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__jGwKb
                        )}
                        flat={"flat"}
                        slot={"Magna ullamcorper ut arcu nisi a per facilisis."}
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__zxKTs
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Production-ready"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__elbFn
                        )}
                        flat={"flat"}
                        slot={
                          "Ac lobortis praesent sagittis dictumst fermentum vestibulum nunc."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__aqiig
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Magical"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__wumQq
                        )}
                        flat={"flat"}
                        slot={
                          "A parturient mi suspendisse nisl inceptos nullam a."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__gayBj
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Accessible"}
                      </Valueprop>
                    </p.Stack>
                  </p.Stack>
                </React.Fragment>
              }
            />
          </div>

          <div
            className={classNames(defaultcss.all, sty.box__mZ0BW)}
            id={"features"}
          >
            <ValuesSection2Dark
              data-plasmic-name={"valuesSection2Dark"}
              data-plasmic-override={overrides.valuesSection2Dark}
            />
          </div>

          <div
            className={classNames(defaultcss.all, sty.box___73RN1)}
            id={"pricing"}
          >
            <PricingSection3
              data-plasmic-name={"pricingSection3"}
              data-plasmic-override={overrides.pricingSection3}
              foreground={
                <React.Fragment>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__upMv3)}
                  >
                    <div className={classNames(defaultcss.all, sty.box__e04Hm)}>
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__tczjE
                        )}
                      >
                        {"Pricing plans"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__ue94
                      )}
                    >
                      {
                        "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__mlq4)}
                  >
                    <div className={classNames(defaultcss.all, sty.box__dxyVe)}>
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__tk3V4)}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__dJLl
                          )}
                        >
                          {"Starter"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(defaultcss.all, sty.box__ycZqo)}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              sty.box__glbHu
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.box___0L4Wf
                              )}
                            >
                              {"$"}
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.box__sfA
                              )}
                            >
                              {"8"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__ysFhh
                            )}
                          >
                            {"/month"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <Divider
                        className={classNames(
                          "__wab_instance",
                          sty.divider__tdbg8
                        )}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__hV9Go)}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.box___74UzZ
                          )}
                        >
                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop___1ILjj
                            )}
                            flatIcon={"flatIcon"}
                            justDescription={"justDescription"}
                            slot={
                              "Vestibulum mollis odio dictum ultrices facilisis molestie vestibulum"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg___2VFy
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__e2W3Q
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__fipd2
                            )}
                            flatIcon={"flatIcon"}
                            justDescription={"justDescription"}
                            slot={"Mus consequat a justo"}
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__kHmbl
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__cZmB0
                                )}
                                role={"img"}
                              />
                            }
                          />
                        </p.Stack>

                        <Button
                          colors={"white"}
                          extraSmallShadow={"extraSmallShadow"}
                          slot={
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.box___9G09X
                              )}
                            >
                              {"Buy starter"}
                            </div>
                          }
                        />
                      </p.Stack>
                    </div>

                    <div className={classNames(defaultcss.all, sty.box__pqKIt)}>
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__aWbXi)}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__cqW0B
                          )}
                        >
                          {"Pro"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(defaultcss.all, sty.box__g920Q)}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              sty.box__vR86Q
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.box__qBMf
                              )}
                            >
                              {"$"}
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.box__xLlxu
                              )}
                            >
                              {"16"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__ekfPu
                            )}
                          >
                            {"/month"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <Divider
                        className={classNames(
                          "__wab_instance",
                          sty.divider__u5ZYp
                        )}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__c92Au)}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(defaultcss.all, sty.box__xqgdt)}
                        >
                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__sd4Qv
                            )}
                            flatIcon={"flatIcon"}
                            justDescription={"justDescription"}
                            slot={
                              "Ligula primis mollis sem dignissim semper lectus parturient"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__dBgQg
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg___1QaYw
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop___7Vq2L
                            )}
                            flatIcon={"flatIcon"}
                            justDescription={"justDescription"}
                            slot={
                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.box__dvFYp
                                )}
                              >
                                {
                                  "A curabitur dignissim pharetra porta suscipit"
                                }
                              </div>
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__t16Nr
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg___0X5Cb
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__q9HaK
                            )}
                            flatIcon={"flatIcon"}
                            justDescription={"justDescription"}
                            slot={
                              "Condimentum diam a et sapien praesent potenti torquent a eros"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__d1XT
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__wYAoQ
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__yIRjc
                            )}
                            flatIcon={"flatIcon"}
                            justDescription={"justDescription"}
                            slot={
                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.box___9F484
                                )}
                              >
                                {"Conubia in hac eu elementum sodales"}
                              </div>
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__xKgdZ
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__mbemf
                                )}
                                role={"img"}
                              />
                            }
                          />
                        </p.Stack>

                        <Button
                          colors={"green"}
                          extraSmallShadow={"extraSmallShadow"}
                          slot={
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.box__hid4I
                              )}
                            >
                              {"Buy pro"}
                            </div>
                          }
                        />
                      </p.Stack>
                    </div>

                    <div
                      className={classNames(defaultcss.all, sty.box___8A3Pz)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__cUjYv)}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___3X2X6
                          )}
                        >
                          {"Team"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(defaultcss.all, sty.box__b1Hhg)}
                        >
                          <div
                            className={classNames(defaultcss.all, sty.box__k13)}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.box__h2Ey
                              )}
                            >
                              {"$"}
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.box__koVCa
                              )}
                            >
                              {"10"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__zuoC5
                            )}
                          >
                            {"/member"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <Divider
                        className={classNames(
                          "__wab_instance",
                          sty.divider__rHvhf
                        )}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box___3QJjC)}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(defaultcss.all, sty.box__j9YpH)}
                        >
                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop___5DNzd
                            )}
                            flatIcon={"flatIcon"}
                            justDescription={"justDescription"}
                            slot={"Ad nam curae a potenti platea"}
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg___96Tde
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__wr3R
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__t57Ip
                            )}
                            flatIcon={"flatIcon"}
                            justDescription={"justDescription"}
                            slot={
                              "A adipiscing scelerisque pretium consectetur sem"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__jgScF
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg___103RW
                                )}
                                role={"img"}
                              />
                            }
                          />
                        </p.Stack>

                        <Button
                          colors={"white"}
                          extraSmallShadow={"extraSmallShadow"}
                          slot={
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.box__ztRyM
                              )}
                            >
                              {"Buy team"}
                            </div>
                          }
                        />
                      </p.Stack>
                    </div>
                  </p.Stack>
                </React.Fragment>
              }
            />
          </div>

          <ShopBanners
            data-plasmic-name={"shopBanners"}
            data-plasmic-override={overrides.shopBanners}
            className={classNames("__wab_instance", sty.shopBanners)}
          >
            <Banner
              className={classNames("__wab_instance", sty.banner___2Vdvi)}
              left={
                <React.Fragment>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__aZhBn
                    )}
                  >
                    {"Sunglasses Collection"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__lwf6B
                    )}
                  >
                    {"Get 25% off on selected items"}
                  </div>

                  <Button
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box___8AZlL
                        )}
                      >
                        {"Go to collection ->"}
                      </div>
                    }
                  />
                </React.Fragment>
              }
            />

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__mtljp)}
            >
              <Banner
                className={classNames("__wab_instance", sty.banner__fofVc)}
                left={
                  <React.Fragment>
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__aGbA6
                      )}
                    >
                      {"Sunglasses Collection"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__rPsxg
                      )}
                    >
                      {"Get 25% off on selected items"}
                    </div>

                    <Button
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__vpiEz
                          )}
                        >
                          {"Go to collection ->"}
                        </div>
                      }
                    />
                  </React.Fragment>
                }
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__osazT)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1463100099107-aa0980c362e6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2850&q=80"
                  }
                />
              </Banner>

              <Banner
                className={classNames("__wab_instance", sty.banner___0KMIj)}
                left={
                  <React.Fragment>
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__ii8Pf
                      )}
                    >
                      {"Sunglasses Collection"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__n1SmV
                      )}
                    >
                      {"Get 25% off on selected items"}
                    </div>

                    <Button
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__cfAxT
                          )}
                        >
                          {"Go to collection ->"}
                        </div>
                      }
                    />
                  </React.Fragment>
                }
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__al34C)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1554568218-0f1715e72254?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1834&q=80"
                  }
                />
              </Banner>
            </p.Stack>
          </ShopBanners>

          <LogoCloudSection2
            data-plasmic-name={"logoCloudSection2"}
            data-plasmic-override={overrides.logoCloudSection2}
            className={classNames("__wab_instance", sty.logoCloudSection2)}
          />

          <div
            className={classNames(defaultcss.all, sty.box___5MFoT)}
            id={"testimonials"}
          >
            <TestimonialsSection1
              data-plasmic-name={"testimonialsSection1"}
              data-plasmic-override={overrides.testimonialsSection1}
            >
              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__fmpyh)}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___1K402)}
                    role={"img"}
                    src={
                      "https://www.caa.com/sites/default/files/styles/headshot_500x500/public/speaker-headshots/Morgan_CAAspeakers_Heashot_Web.jpg?itok=WCOhQ1Hj"
                    }
                  />
                }
              />

              <Testimonial
                className={classNames(
                  "__wab_instance",
                  sty.testimonial___47Nwo
                )}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__wjn1M)}
                    role={"img"}
                    src={
                      "https://tv-fanatic-res.cloudinary.com/iu/s--eXCbHIe1--/t_teaser_wide/cs_srgb,f_auto,fl_strip_profile.lossy,q_auto:420/v1371156342/elaine-benes-picture.png"
                    }
                  />
                }
                slot2={"Elaine Benes"}
                slot3={"Editor, Pendant Publishing"}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__cNDqV
                  )}
                >
                  {'"Vestibulum lacinia varius habitant dis aenean.'}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__ckUot
                  )}
                >
                  {
                    'A parturient non ultricies a parturient leo a nascetur at consectetur turpis praesent mus ornare nulla posuere vel parturient."'
                  }
                </div>
              </Testimonial>

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__ksOyn)}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___8V4N)}
                    role={"img"}
                    src={
                      "https://i.pinimg.com/originals/87/d7/7d/87d77d68368fe5361d535b51cc5af09a.jpg"
                    }
                  />
                }
                slot2={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__riBpU
                    )}
                  >
                    {"Woody Boyd"}
                  </div>
                }
                slot3={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___9VBr
                    )}
                  >
                    {"Assistant Bartender, Cheers"}
                  </div>
                }
              >
                {
                  '"A ullamcorper etiam gravida a non maecenas ac parturient lectus vestibulum nam."'
                }
              </Testimonial>

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__uBf1Y)}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__jF5QJ)}
                    role={"img"}
                    src={
                      "https://a1cf74336522e87f135f-2f21ace9a6cf0052456644b80fa06d4f.ssl.cf2.rackcdn.com/images/characters_opt/p-fresh-randall-park.jpg"
                    }
                  />
                }
                slot2={"Louis Huang"}
                slot3={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__aZleR
                    )}
                  >
                    {"Restaurant Owner, Cattleman's Ranch"}
                  </div>
                }
              >
                {
                  '"Purus dis a primis rhoncus blandit velit suspendisse porta at ullamcorper suscipit a scelerisque sed pharetra facilisi vitae."'
                }
              </Testimonial>
            </TestimonialsSection1>
          </div>

          <CallToActionSection1
            data-plasmic-name={"callToActionSection1"}
            data-plasmic-override={overrides.callToActionSection1}
            className={classNames("__wab_instance", sty.callToActionSection1)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "heroSection2",
    "navigation",
    "valuesSection3",
    "h2",
    "valuesSection2Dark",
    "pricingSection3",
    "shopBanners",
    "logoCloudSection2",
    "testimonialsSection1",
    "callToActionSection1"
  ],

  heroSection2: ["heroSection2", "navigation"],
  navigation: ["navigation"],
  valuesSection3: ["valuesSection3", "h2"],
  h2: ["h2"],
  valuesSection2Dark: ["valuesSection2Dark"],
  pricingSection3: ["pricingSection3"],
  shopBanners: ["shopBanners"],
  logoCloudSection2: ["logoCloudSection2"],
  testimonialsSection1: ["testimonialsSection1"],
  callToActionSection1: ["callToActionSection1"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    heroSection2: makeNodeComponent("heroSection2"),
    navigation: makeNodeComponent("navigation"),
    valuesSection3: makeNodeComponent("valuesSection3"),
    h2: makeNodeComponent("h2"),
    valuesSection2Dark: makeNodeComponent("valuesSection2Dark"),
    pricingSection3: makeNodeComponent("pricingSection3"),
    shopBanners: makeNodeComponent("shopBanners"),
    logoCloudSection2: makeNodeComponent("logoCloudSection2"),
    testimonialsSection1: makeNodeComponent("testimonialsSection1"),
    callToActionSection1: makeNodeComponent("callToActionSection1"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
