// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicHeroSection4 } from "./plasmic/landing_kit/PlasmicHeroSection4";

function HeroSection4_(props, ref) {
  // Use PlasmicHeroSection4 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicHeroSection4 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all HeroSection4Props here, but feel free
  // to do whatever works for you.
  return <PlasmicHeroSection4 root={{ ref }} {...props} />;
}

const HeroSection4 = React.forwardRef(HeroSection4_);

export default HeroSection4;
