// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3SwC2F4BeXucfS9cpFbd24
// Component: imX9BlF4Uj8
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: QaipWgLIw8/component
import Valueprop from "../../Valueprop"; // plasmic-import: YnVQB3eyyN/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: K7Rqgqmh9OYf/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_kit.module.css"; // plasmic-import: 3SwC2F4BeXucfS9cpFbd24/projectcss
import * as sty from "./PlasmicPricingSection2.module.css"; // plasmic-import: imX9BlF4Uj8/css
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: h9S1yezhrN/icon

export const PlasmicPricingSection2__VariantProps = new Array();

export const PlasmicPricingSection2__ArgProps = new Array(
  "foreground",
  "foreground2"
);

function PlasmicPricingSection2__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"foreground"}
        data-plasmic-override={overrides.foreground}
        hasGap={true}
        className={classNames(defaultcss.all, sty.foreground)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <div className={classNames(defaultcss.all, sty.box___7IFr0)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__jrZFv
                  )}
                >
                  {"Simple pricing for everyone"}
                </div>
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__yuBVj
                )}
              >
                {
                  "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                }
              </div>
            </React.Fragment>
          ),

          value: args.foreground
        })}
      </p.Stack>

      <p.Stack
        as={"div"}
        data-plasmic-name={"foreground2"}
        data-plasmic-override={overrides.foreground2}
        hasGap={true}
        className={classNames(defaultcss.all, sty.foreground2)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <div className={classNames(defaultcss.all, sty.box__aT7PV)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__q1Jhv)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__yzIh3)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__xKyJr
                      )}
                    >
                      {"Starter"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__rrYSx
                      )}
                    >
                      {"All the basics"}
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__kzdwW)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__vf62A
                      )}
                    >
                      {"Free"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__z0Kr
                      )}
                    >
                      {"Forever"}
                    </div>
                  </p.Stack>

                  <Button darkGray={"darkGray"} slot={"Get started"} />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__lyFRl)}
                >
                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop__jeafo
                    )}
                    flatIcon={"flatIcon"}
                    justDescription={"justDescription"}
                    slot={
                      "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                    }
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__iz9UF)}
                        role={"img"}
                      />
                    }
                    slot22={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__rDkxr)}
                        role={"img"}
                      />
                    }
                  />

                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop__sW6Gd
                    )}
                    flatIcon={"flatIcon"}
                    justDescription={"justDescription"}
                    slot={
                      "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                    }
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__coNGf)}
                        role={"img"}
                      />
                    }
                    slot22={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg___3O8J2)}
                        role={"img"}
                      />
                    }
                  />
                </p.Stack>
              </div>

              <div className={classNames(defaultcss.all, sty.box__eBiIc)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__t7Lv2)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__c5OEb)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__y072
                      )}
                    >
                      {"Pro"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__fmxdz
                      )}
                    >
                      {"Best deal"}
                    </div>
                  </p.Stack>

                  <div className={classNames(defaultcss.all, sty.box__yi98T)}>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__lH4Nx)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box___5XvPz
                        )}
                      >
                        {"$"}
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__ykk1L
                        )}
                      >
                        {"7.99"}
                      </div>
                    </p.Stack>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__k6Y4U
                      )}
                    >
                      {"/mo"}
                    </div>
                  </div>

                  <Button
                    colors={"white"}
                    extraSmallShadow={"extraSmallShadow"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__itD1T
                        )}
                      >
                        {"Purchase pro"}
                      </div>
                    }
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__vxcOg)}
                >
                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop___1Y0Pb
                    )}
                    flatIcon={"flatIcon"}
                    justDescription={"justDescription"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__oo5Gt
                        )}
                      >
                        {
                          "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                        }
                      </div>
                    }
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__nBqAj)}
                        role={"img"}
                      />
                    }
                    slot22={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__knktc)}
                        role={"img"}
                      />
                    }
                  />

                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop__ir3Fc
                    )}
                    flatIcon={"flatIcon"}
                    justDescription={"justDescription"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__rSdiG
                        )}
                      >
                        {
                          "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                        }
                      </div>
                    }
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__lvO48)}
                        role={"img"}
                      />
                    }
                    slot22={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__yADyF)}
                        role={"img"}
                      />
                    }
                  />

                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop__f8Idm
                    )}
                    flatIcon={"flatIcon"}
                    justDescription={"justDescription"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__toNhX
                        )}
                      >
                        {
                          "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                        }
                      </div>
                    }
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__lnaCb)}
                        role={"img"}
                      />
                    }
                    slot22={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__bJmlb)}
                        role={"img"}
                      />
                    }
                  />
                </p.Stack>
              </div>

              <div className={classNames(defaultcss.all, sty.box__xSvxP)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box___3O9)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__rdnJa)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__ilAkZ
                      )}
                    >
                      {"Team"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__nOMso
                      )}
                    >
                      {"Level up"}
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__sPk8Q)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__muhXs)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__yxoO9
                        )}
                      >
                        {"$"}
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__bopFz
                        )}
                      >
                        {"23.99"}
                      </div>
                    </p.Stack>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box___7TF2H
                      )}
                    >
                      {"/mo"}
                    </div>
                  </p.Stack>

                  <Button colors={"green"} slot={"Get started"} />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__ljJgo)}
                >
                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop__rzGbL
                    )}
                    flatIcon={"flatIcon"}
                    justDescription={"justDescription"}
                    slot={
                      "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                    }
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__uI8Um)}
                        role={"img"}
                      />
                    }
                    slot22={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__e2BXo)}
                        role={"img"}
                      />
                    }
                  />

                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop__rzKdq
                    )}
                    flatIcon={"flatIcon"}
                    justDescription={"justDescription"}
                    slot={
                      "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                    }
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__sXb5N)}
                        role={"img"}
                      />
                    }
                    slot22={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__tZ8S9)}
                        role={"img"}
                      />
                    }
                  />

                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop__k6YW8
                    )}
                    flatIcon={"flatIcon"}
                    justDescription={"justDescription"}
                    slot={
                      "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                    }
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__agtUj)}
                        role={"img"}
                      />
                    }
                    slot22={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__pYNdx)}
                        role={"img"}
                      />
                    }
                  />

                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop___1Mbqu
                    )}
                    flatIcon={"flatIcon"}
                    justDescription={"justDescription"}
                    slot={
                      "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                    }
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__m4AEz)}
                        role={"img"}
                      />
                    }
                    slot22={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__gOQsG)}
                        role={"img"}
                      />
                    }
                  />

                  <Valueprop
                    className={classNames(
                      "__wab_instance",
                      sty.valueprop__noeRg
                    )}
                    flatIcon={"flatIcon"}
                    justDescription={"justDescription"}
                    slot={
                      "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                    }
                    slot2={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__kljzu)}
                        role={"img"}
                      />
                    }
                    slot22={
                      <Icon14Icon
                        className={classNames(defaultcss.all, sty.svg__g1KP9)}
                        role={"img"}
                      />
                    }
                  />
                </p.Stack>
              </div>
            </React.Fragment>
          ),

          value: args.foreground2
        })}
      </p.Stack>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "foreground", "foreground2"],
  foreground: ["foreground"],
  foreground2: ["foreground2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPricingSection2__ArgProps,
      internalVariantPropNames: PlasmicPricingSection2__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicPricingSection2__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPricingSection2";
  } else {
    func.displayName = `PlasmicPricingSection2.${nodeName}`;
  }
  return func;
}

export const PlasmicPricingSection2 = Object.assign(
  // Top-level PlasmicPricingSection2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    foreground: makeNodeComponent("foreground"),
    foreground2: makeNodeComponent("foreground2"),
    // Metadata about props expected for PlasmicPricingSection2
    internalVariantProps: PlasmicPricingSection2__VariantProps,
    internalArgProps: PlasmicPricingSection2__ArgProps
  }
);

export default PlasmicPricingSection2;
/* prettier-ignore-end */
