// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3SwC2F4BeXucfS9cpFbd24
// Component: _J0GKW5UfD
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_kit.module.css"; // plasmic-import: 3SwC2F4BeXucfS9cpFbd24/projectcss
import * as sty from "./PlasmicLogoCloudSection1.module.css"; // plasmic-import: _J0GKW5UfD/css
import loomsvgSy6AtFLcw from "./images/loomsvg.svg"; // plasmic-import: sy_6atFLcw/picture
import strapisvg5F5IMh5Zc8 from "./images/strapisvg.svg"; // plasmic-import: 5F5iMh5Zc8/picture
import segmentsvgN3D57Bi7EY from "./images/segmentsvg.svg"; // plasmic-import: N3d57bi7eY/picture
import xstatesvgRnRxAcJptj from "./images/xstatesvg.svg"; // plasmic-import: RNRxAcJptj/picture
import mapboxsvg3C7LpGysKw from "./images/mapboxsvg.svg"; // plasmic-import: 3C7lpGYSKw/picture

export const PlasmicLogoCloudSection1__VariantProps = new Array();

export const PlasmicLogoCloudSection1__ArgProps = new Array("children");

function PlasmicLogoCloudSection1__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___7CmlA)}
                role={"img"}
                src={loomsvgSy6AtFLcw}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___4VYl4)}
                role={"img"}
                src={strapisvg5F5IMh5Zc8}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__eiBiu)}
                role={"img"}
                src={segmentsvgN3D57Bi7EY}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__lkggX)}
                role={"img"}
                src={xstatesvgRnRxAcJptj}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___6QAbC)}
                role={"img"}
                src={mapboxsvg3C7LpGysKw}
              />
            </React.Fragment>
          ),

          value: args.children
        })}
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLogoCloudSection1__ArgProps,
      internalVariantPropNames: PlasmicLogoCloudSection1__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicLogoCloudSection1__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLogoCloudSection1";
  } else {
    func.displayName = `PlasmicLogoCloudSection1.${nodeName}`;
  }
  return func;
}

export const PlasmicLogoCloudSection1 = Object.assign(
  // Top-level PlasmicLogoCloudSection1 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    // Metadata about props expected for PlasmicLogoCloudSection1
    internalVariantProps: PlasmicLogoCloudSection1__VariantProps,
    internalArgProps: PlasmicLogoCloudSection1__ArgProps
  }
);

export default PlasmicLogoCloudSection1;
/* prettier-ignore-end */
