// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3SwC2F4BeXucfS9cpFbd24
// Component: IaLiG14Rft
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_kit.module.css"; // plasmic-import: 3SwC2F4BeXucfS9cpFbd24/projectcss
import * as sty from "./PlasmicLogoCloudSection2.module.css"; // plasmic-import: IaLiG14Rft/css
import loomsvg29DAqs93KiL from "./images/loomsvg2.svg"; // plasmic-import: 9dAqs93KiL/picture
import strapisvg2UlrRk0Hz2R from "./images/strapisvg2.svg"; // plasmic-import: UlrRK0hz2r/picture
import segmentsvg2PjQjPdq9CN from "./images/segmentsvg2.svg"; // plasmic-import: PJQjPdq9cN/picture
import xstate1SvgMTjmTho0Y7 from "./images/xstate1Svg.svg"; // plasmic-import: MTjmTHO0y7/picture
import mapboxsvg2FSSctBwiA from "./images/mapboxsvg2.svg"; // plasmic-import: fS_SCTBwiA/picture

export const PlasmicLogoCloudSection2__VariantProps = new Array();

export const PlasmicLogoCloudSection2__ArgProps = new Array("children");

function PlasmicLogoCloudSection2__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___6AFpM)}
                role={"img"}
                src={loomsvg29DAqs93KiL}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__d8Aex)}
                role={"img"}
                src={strapisvg2UlrRk0Hz2R}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__mGh8P)}
                role={"img"}
                src={segmentsvg2PjQjPdq9CN}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__o13L)}
                role={"img"}
                src={xstate1SvgMTjmTho0Y7}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__tlZnF)}
                role={"img"}
                src={mapboxsvg2FSSctBwiA}
              />
            </React.Fragment>
          ),

          value: args.children
        })}
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLogoCloudSection2__ArgProps,
      internalVariantPropNames: PlasmicLogoCloudSection2__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicLogoCloudSection2__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLogoCloudSection2";
  } else {
    func.displayName = `PlasmicLogoCloudSection2.${nodeName}`;
  }
  return func;
}

export const PlasmicLogoCloudSection2 = Object.assign(
  // Top-level PlasmicLogoCloudSection2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    // Metadata about props expected for PlasmicLogoCloudSection2
    internalVariantProps: PlasmicLogoCloudSection2__VariantProps,
    internalArgProps: PlasmicLogoCloudSection2__ArgProps
  }
);

export default PlasmicLogoCloudSection2;
/* prettier-ignore-end */
