// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3SwC2F4BeXucfS9cpFbd24
// Component: n_i8KKxAL4
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: QaipWgLIw8/component
import Category from "../../Category"; // plasmic-import: MuQdqaRx3L/component
import IconCategory from "../../IconCategory"; // plasmic-import: TzSKfCEIuj/component
import ShopBanners from "../../ShopBanners"; // plasmic-import: cmWRjF4k6DZ/component
import Price from "../../Price"; // plasmic-import: -ltGw8pif2/component
import ListItem from "../../ListItem"; // plasmic-import: AfVvaVT7MR/component
import ProductCard from "../../ProductCard"; // plasmic-import: aXvFg-kEwT/component
import Tag from "../../Tag"; // plasmic-import: dCWwOvecYH/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: K7Rqgqmh9OYf/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_kit.module.css"; // plasmic-import: 3SwC2F4BeXucfS9cpFbd24/projectcss
import * as sty from "./PlasmicShop.module.css"; // plasmic-import: n_i8KKxAL4/css
import Icon25Icon from "./icons/PlasmicIcon__Icon25"; // plasmic-import: 4-rt81qQUT/icon
import Icon26Icon from "./icons/PlasmicIcon__Icon26"; // plasmic-import: kiCS_P_bBf/icon
import Icon27Icon from "./icons/PlasmicIcon__Icon27"; // plasmic-import: 24yWQ0QNNz/icon
import Icon29Icon from "./icons/PlasmicIcon__Icon29"; // plasmic-import: AYQQDPIzjN/icon
import Icon35Icon from "./icons/PlasmicIcon__Icon35"; // plasmic-import: XDLlJBkpeL/icon
import Icon30Icon from "./icons/PlasmicIcon__Icon30"; // plasmic-import: HMm7wJ5BWy/icon
import Icon31Icon from "./icons/PlasmicIcon__Icon31"; // plasmic-import: O1BAixSaeO/icon
import Icon32Icon from "./icons/PlasmicIcon__Icon32"; // plasmic-import: FDbd6sO4RE/icon
import Icon33Icon from "./icons/PlasmicIcon__Icon33"; // plasmic-import: VHFKoT2Pwt/icon
import Icon37Icon from "./icons/PlasmicIcon__Icon37"; // plasmic-import: A54nHQGwYN/icon

export const PlasmicShop__VariantProps = new Array();

export const PlasmicShop__ArgProps = new Array();

function PlasmicShop__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <p.Stack
            as={"section"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.section__m64Fk)}
          >
            <div className={classNames(defaultcss.all, sty.box___8LkP)}>
              <div className={classNames(defaultcss.all, sty.box__jOmCi)}>
                <h3
                  className={classNames(
                    defaultcss.h3,
                    defaultcss.__wab_text,
                    sty.h3__hofXp
                  )}
                >
                  {"Shop by category"}
                </h3>

                <Button
                  className={classNames("__wab_instance", sty.button__qfIuH)}
                  slot={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__lkXnx
                      )}
                    >
                      {"Browse all ->"}
                    </div>
                  }
                />
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__aiUaf)}
            >
              <div className={classNames(defaultcss.all, sty.box__it1Ar)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___4IsCz
                  )}
                >
                  {"New arrivals"}
                </div>
              </div>

              <div className={classNames(defaultcss.all, sty.box___00Qgr)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__criTm
                  )}
                >
                  {"Womens"}
                </div>
              </div>

              <div className={classNames(defaultcss.all, sty.box__xd5B0)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__uytTh
                  )}
                >
                  {"Mens"}
                </div>
              </div>

              <div className={classNames(defaultcss.all, sty.box___6FuE)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__oyTzi
                  )}
                >
                  {"Accessories"}
                </div>
              </div>

              <div className={classNames(defaultcss.all, sty.box__sWeiR)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__pFhm2
                  )}
                >
                  {"On sale"}
                </div>
              </div>
            </p.Stack>
          </p.Stack>

          <p.Stack
            as={"section"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.section__vxuqf)}
          >
            <div className={classNames(defaultcss.all, sty.box__wt95N)}>
              <div className={classNames(defaultcss.all, sty.box__oh3F4)}>
                <h3
                  className={classNames(
                    defaultcss.h3,
                    defaultcss.__wab_text,
                    sty.h3__hzpCu
                  )}
                >
                  {"Shop by category"}
                </h3>

                <Button
                  className={classNames("__wab_instance", sty.button___5Kp4V)}
                  slot={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__mu1R5
                      )}
                    >
                      {"Browse all ->"}
                    </div>
                  }
                />
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__gLUu)}
            >
              <Category
                className={classNames("__wab_instance", sty.category__tnflY)}
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__qJni)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1488371934083-edb7857977df?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=928&q=80"
                  }
                />

                <div className={classNames(defaultcss.all, sty.box__i0G1I)} />
              </Category>

              <Category
                className={classNames("__wab_instance", sty.category__lnRf)}
                slot={"Womens"}
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__eQ1AV)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1552664199-fd31f7431a55?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=3034&q=80"
                  }
                />

                <div className={classNames(defaultcss.all, sty.box__u1Vmb)} />
              </Category>

              <Category
                className={classNames("__wab_instance", sty.category__y40G)}
                slot={"Mens"}
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__c1AkF)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1530882548122-0596ee66cdfd?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=934&q=80"
                  }
                />

                <div className={classNames(defaultcss.all, sty.box__dDwOv)} />
              </Category>

              <Category
                className={classNames("__wab_instance", sty.category__t4Uch)}
                slot={"Kids"}
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__rw5Cz)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1593811044950-7f45aac20843?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2100&q=80"
                  }
                />

                <div className={classNames(defaultcss.all, sty.box__eCzD)} />
              </Category>

              <Category
                className={classNames("__wab_instance", sty.category___1B9OV)}
                slot={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__qIiol
                    )}
                  >
                    {"Accessories"}
                  </div>
                }
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__x5Pq)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1568388200282-75083345400e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2897&q=80"
                  }
                />

                <div className={classNames(defaultcss.all, sty.box__jfpkT)} />
              </Category>

              <Category
                className={classNames("__wab_instance", sty.category__p2AlM)}
                slot={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__i52X2
                    )}
                  >
                    {"On sale"}
                  </div>
                }
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img___3KXoE)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1576566588028-4147f3842f27?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80"
                  }
                />

                <div className={classNames(defaultcss.all, sty.box__boAl8)} />
              </Category>

              <Category
                className={classNames("__wab_instance", sty.category__bLumI)}
                slot={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__gUoIu
                    )}
                  >
                    {"Limited"}
                  </div>
                }
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__anhP)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1592278743983-1bdf837dd459?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=934&q=80"
                  }
                />

                <div className={classNames(defaultcss.all, sty.box__svWbt)} />
              </Category>
            </p.Stack>
          </p.Stack>

          <p.Stack
            as={"section"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.section__roKnp)}
          >
            <div className={classNames(defaultcss.all, sty.box__iF691)}>
              <div className={classNames(defaultcss.all, sty.box__fdUnv)}>
                <h3
                  className={classNames(
                    defaultcss.h3,
                    defaultcss.__wab_text,
                    sty.h3___4Fd0F
                  )}
                >
                  {"Shop by category"}
                </h3>

                <Button
                  className={classNames("__wab_instance", sty.button__nDfOu)}
                  slot={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__c6JGk
                      )}
                    >
                      {"Browse all ->"}
                    </div>
                  }
                />
              </div>
            </div>

            <div className={classNames(defaultcss.all, sty.box___0V7Y)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__mvzZk)}
              >
                <IconCategory>
                  <Icon25Icon
                    className={classNames(defaultcss.all, sty.svg__nctz8)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___17NuL
                    )}
                  >
                    {"Shirts"}
                  </div>
                </IconCategory>

                <IconCategory>
                  <Icon26Icon
                    className={classNames(defaultcss.all, sty.svg___8NSiB)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__jxU5S
                    )}
                  >
                    {"Bags"}
                  </div>
                </IconCategory>

                <IconCategory>
                  <Icon27Icon
                    className={classNames(defaultcss.all, sty.svg___09Mfk)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___27GAg
                    )}
                  >
                    {"Sofas"}
                  </div>
                </IconCategory>

                <IconCategory>
                  <Icon29Icon
                    className={classNames(defaultcss.all, sty.svg___9WVa)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__k0ClM
                    )}
                  >
                    {"Glasses"}
                  </div>
                </IconCategory>

                <IconCategory>
                  <Icon35Icon
                    className={classNames(defaultcss.all, sty.svg__swohb)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___0DhA0
                    )}
                  >
                    {"Glasses"}
                  </div>
                </IconCategory>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__cJ1Ff)}
              >
                <IconCategory>
                  <Icon30Icon
                    className={classNames(defaultcss.all, sty.svg__tavTi)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__nmPhq
                    )}
                  >
                    {"Jewelry"}
                  </div>
                </IconCategory>

                <IconCategory>
                  <Icon31Icon
                    className={classNames(defaultcss.all, sty.svg__uFdGs)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__goAw4
                    )}
                  >
                    {"Shoes"}
                  </div>
                </IconCategory>

                <IconCategory>
                  <Icon32Icon
                    className={classNames(defaultcss.all, sty.svg__jSovj)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__ndmfi
                    )}
                  >
                    {"Lamps"}
                  </div>
                </IconCategory>

                <IconCategory>
                  <Icon33Icon
                    className={classNames(defaultcss.all, sty.svg__dOpKb)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__dWPv
                    )}
                  >
                    {"Tables"}
                  </div>
                </IconCategory>

                <IconCategory>
                  <Icon37Icon
                    className={classNames(defaultcss.all, sty.svg___5Pdn3)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__naFg4
                    )}
                  >
                    {"Tables"}
                  </div>
                </IconCategory>
              </p.Stack>
            </div>
          </p.Stack>

          <ShopBanners
            data-plasmic-name={"shopBanners"}
            data-plasmic-override={overrides.shopBanners}
            className={classNames("__wab_instance", sty.shopBanners)}
          />

          <section className={classNames(defaultcss.all, sty.section__aXjoC)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box___3VLfR)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__q49R)}
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__q52Dd)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1491637639811-60e2756cc1c7?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=969&q=80"
                  }
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__ughrT)}
                >
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__yyAI)}
                    role={"img"}
                    src={
                      "https://images.unsplash.com/photo-1474376962954-d8a681cc53b2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=934&q=80"
                    }
                  />

                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__fFbwF)}
                    role={"img"}
                    src={
                      "https://images.unsplash.com/photo-1547949003-9792a18a2601?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2100&q=80"
                    }
                  />

                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___8SpE)}
                    role={"img"}
                    src={
                      "https://images.unsplash.com/photo-1522713360981-e014ec8de332?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=975&q=80"
                    }
                  />
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__j47TK)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__wbv8
                  )}
                >
                  {"Enter some text"}
                </div>

                <Price
                  className={classNames("__wab_instance", sty.price___7HlIc)}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__ucdqr)}
                >
                  <Button colors={"green"} slot={"Add to cart"} />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__uRDqN)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__nx177
                    )}
                  >
                    {
                      "Scelerisque natoque nisl pulvinar netus purus aptent potenti dis nisl vestibulum quisque pretium molestie diam a accumsan nulla dapibus amet odio. In a magnis viverra diam imperdiet a ut viverra suspendisse semper nisi molestie ultricies a eu non integer sed."
                    }
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___9Pool
                    )}
                  >
                    {
                      "Ullamcorper nisi egestas vestibulum primis feugiat mus hac eros per molestie urna tristique ullamcorper ut donec vestibulum a sit a a a nunc interdum at laoreet ultrices."
                    }
                  </div>
                </p.Stack>

                <div className={classNames(defaultcss.all, sty.box__uWdvu)}>
                  <ListItem
                    bottomBorder={"light"}
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__wP7Y9
                    )}
                    leftCheck={"leftCheck"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__dMmXv
                      )}
                    >
                      {"Potenti mus id in sem sem id non."}
                    </div>
                  </ListItem>

                  <ListItem
                    bottomBorder={"light"}
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__puzzi
                    )}
                    leftCheck={"leftCheck"}
                  >
                    {
                      "Dictumst felis rhoncus suspendisse dignissim per feugiat nam."
                    }
                  </ListItem>

                  <ListItem
                    bottomBorder={"light"}
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__mqCwo
                    )}
                    leftCheck={"leftCheck"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__dXvh9
                      )}
                    >
                      {
                        "In ad nostra imperdiet parturient parturient netus praesent tellus elementum velit facilisis."
                      }
                    </div>
                  </ListItem>

                  <ListItem
                    bottomBorder={"light"}
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__pAlvw
                    )}
                    leftCheck={"leftCheck"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__k0Qzf
                      )}
                    >
                      {
                        "Leo laoreet ad ac mi amet ultricies pulvinar a mattis lorem a erat elementum cras a."
                      }
                    </div>
                  </ListItem>

                  <ListItem
                    className={classNames(
                      "__wab_instance",
                      sty.listItem__kQNpu
                    )}
                    leftCheck={"leftCheck"}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__yoN4O
                      )}
                    >
                      {"Tristique leo aliquet ullamcorper curae parturient."}
                    </div>
                  </ListItem>
                </div>
              </p.Stack>
            </p.Stack>
          </section>

          <p.Stack
            as={"section"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.section__j5MNc)}
          >
            <div className={classNames(defaultcss.all, sty.box__xLp3C)}>
              <h3
                className={classNames(
                  defaultcss.h3,
                  defaultcss.__wab_text,
                  sty.h3__rCfvg
                )}
              >
                {"Flash sale!"}
              </h3>

              <Button
                className={classNames("__wab_instance", sty.button___6Eqdh)}
                slot={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___6CytL
                    )}
                  >
                    {"Browse all ->"}
                  </div>
                }
              />
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__p5H8)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__kDlq5)}
                slot2={
                  <React.Fragment>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__ul5EZ)}
                    >
                      {false ? (
                        <Tag
                          className={classNames(
                            "__wab_instance",
                            sty.tag__tAKl
                          )}
                        />
                      ) : null}

                      <Tag
                        children22={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__nkCdG
                            )}
                          >
                            {"sale"}
                          </div>
                        }
                        className={classNames("__wab_instance", sty.tag__vxFui)}
                      />
                    </p.Stack>

                    <h3
                      className={classNames(
                        defaultcss.h3,
                        defaultcss.__wab_text,
                        sty.h3__aVh2E
                      )}
                    >
                      {"Men's running shoes"}
                    </h3>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__vUy9B)}
                    >
                      <Price />

                      <Price
                        slot={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__peXcX
                            )}
                          >
                            {"$"}
                          </div>
                        }
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___07B3P
                          )}
                        >
                          {"150"}
                        </div>

                        {false ? (
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__korP4
                            )}
                          >
                            {".00"}
                          </div>
                        ) : null}
                      </Price>
                    </p.Stack>
                  </React.Fragment>
                }
                slot3={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__ieDev)}
                    role={"img"}
                    src={
                      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/yi2ygcpplrnzcwvsnanl/free-rn-2018-mens-running-shoe-4VTnGqeZ.png"
                    }
                  />
                }
              />

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___5N8CZ
                )}
                slot2={
                  <React.Fragment>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box___61KnW)}
                    >
                      {false ? (
                        <Tag
                          className={classNames(
                            "__wab_instance",
                            sty.tag___0Zf1
                          )}
                        />
                      ) : null}

                      <Tag
                        children22={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__o829D
                            )}
                          >
                            {"sale"}
                          </div>
                        }
                        className={classNames("__wab_instance", sty.tag__zjEs3)}
                      />

                      <Tag
                        children22={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__k6Qx
                            )}
                          >
                            {"just in"}
                          </div>
                        }
                        className={classNames("__wab_instance", sty.tag__psva)}
                      />
                    </p.Stack>

                    <h3
                      className={classNames(
                        defaultcss.h3,
                        defaultcss.__wab_text,
                        sty.h3__z9IlE
                      )}
                    >
                      {"Kids classic tennis shoes"}
                    </h3>

                    <Price
                      className={classNames("__wab_instance", sty.price__d7B9J)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__aXt0E
                        )}
                      >
                        {"64"}
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__r9WuN
                        )}
                      >
                        {"99"}
                      </div>
                    </Price>
                  </React.Fragment>
                }
                slot3={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___3WKJb)}
                    role={"img"}
                    src={
                      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/b67ca232-2b73-40dd-b76f-702070a2b4c7/quest-3-mens-running-shoe-FHR8DM.png"
                    }
                  />
                }
              />

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___6U4Fd
                )}
                slot2={
                  <React.Fragment>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__oF6Kr)}
                    >
                      {false ? (
                        <Tag
                          className={classNames(
                            "__wab_instance",
                            sty.tag___9Zs4K
                          )}
                        />
                      ) : null}

                      <Tag
                        children22={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__tCTnZ
                            )}
                          >
                            {"Fall 2021"}
                          </div>
                        }
                        className={classNames("__wab_instance", sty.tag__pvrl9)}
                      />
                    </p.Stack>

                    <h3
                      className={classNames(
                        defaultcss.h3,
                        defaultcss.__wab_text,
                        sty.h3__qs6Ae
                      )}
                    >
                      {"Fall special sneakers"}
                    </h3>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__iwZ7F)}
                    >
                      <Price>
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__eunx9
                          )}
                        >
                          {"199"}
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___6QsNi
                          )}
                        >
                          {"99"}
                        </div>
                      </Price>

                      <Price
                        slot={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__aOjci
                            )}
                          >
                            {"$"}
                          </div>
                        }
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__fSeyM
                          )}
                        >
                          {"150"}
                        </div>

                        {false ? (
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__p2GC
                            )}
                          >
                            {".00"}
                          </div>
                        ) : null}
                      </Price>
                    </p.Stack>
                  </React.Fragment>
                }
                slot3={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__nNavo)}
                    role={"img"}
                    src={
                      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/0154a28f-06e3-408f-9525-346830f583b7/air-zoom-pegasus-37-womens-running-shoe-Jl0bDf.png"
                    }
                  />
                }
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__cQi7N)}
                slot2={
                  <React.Fragment>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box___2YwNr)}
                    >
                      {false ? (
                        <Tag
                          children22={
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.box__wioks
                              )}
                            >
                              {"Shoes"}
                            </div>
                          }
                          className={classNames(
                            "__wab_instance",
                            sty.tag__dOhTp
                          )}
                        />
                      ) : null}

                      <Tag
                        children22={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__mokcl
                            )}
                          >
                            {"sale"}
                          </div>
                        }
                        className={classNames("__wab_instance", sty.tag__qyfd3)}
                      />

                      <Tag
                        children22={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__azkQs
                            )}
                          >
                            {"eco-friendly"}
                          </div>
                        }
                        className={classNames("__wab_instance", sty.tag__ifwCe)}
                      />
                    </p.Stack>

                    <h3
                      className={classNames(
                        defaultcss.h3,
                        defaultcss.__wab_text,
                        sty.h3__rh0Ie
                      )}
                    >
                      {"Summer edition basketball shoes"}
                    </h3>

                    <Price
                      className={classNames("__wab_instance", sty.price__m0Tc)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__zYh92
                        )}
                      >
                        {"199"}
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__myWf9
                        )}
                      >
                        {"99"}
                      </div>
                    </Price>
                  </React.Fragment>
                }
                slot3={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__fars5)}
                    role={"img"}
                    src={
                      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/23c31bdd-613c-4665-afa8-9b8258fc5dbd/air-vapormax-2020-big-kids-shoe-jCvK2p.png"
                    }
                  />
                }
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__cmmF9)}
                slot2={
                  <React.Fragment>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__gnPb2)}
                    >
                      <Tag
                        className={classNames("__wab_instance", sty.tag__caodn)}
                      />

                      <Tag
                        children22={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__j0Rco
                            )}
                          >
                            {"sale"}
                          </div>
                        }
                        className={classNames(
                          "__wab_instance",
                          sty.tag___90WUk
                        )}
                      />
                    </p.Stack>

                    <h3
                      className={classNames(
                        defaultcss.h3,
                        defaultcss.__wab_text,
                        sty.h3__oPxH1
                      )}
                    >
                      {"Summer special sneakers"}
                    </h3>

                    <Price
                      className={classNames("__wab_instance", sty.price__vmiCx)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__qsHC
                        )}
                      >
                        {"199"}
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__njA0T
                        )}
                      >
                        {"99"}
                      </div>
                    </Price>
                  </React.Fragment>
                }
                slot3={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__wa13B)}
                    role={"img"}
                    src={
                      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/m27j3lbzoxd5ih0xdl7g/flex-control-3-mens-training-shoe-1lFKLq.png"
                    }
                  />
                }
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__gvbYe)}
                slot2={
                  <React.Fragment>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__x7Etk)}
                    >
                      <Tag
                        children22={"winter 2020"}
                        className={classNames("__wab_instance", sty.tag___1EEa)}
                      />

                      <Tag
                        children22={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__wy5Ib
                            )}
                          >
                            {"sale"}
                          </div>
                        }
                        className={classNames("__wab_instance", sty.tag__opLEj)}
                      />
                    </p.Stack>

                    <h3
                      className={classNames(
                        defaultcss.h3,
                        defaultcss.__wab_text,
                        sty.h3__pTnzJ
                      )}
                    >
                      {"Summer special sneakers"}
                    </h3>

                    <Price
                      className={classNames("__wab_instance", sty.price__aAKH)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__qiBG
                        )}
                      >
                        {"199"}
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__igD9C
                        )}
                      >
                        {"99"}
                      </div>
                    </Price>
                  </React.Fragment>
                }
                slot3={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__pcm6T)}
                    role={"img"}
                    src={
                      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/4e731fca-7eae-4a1a-8baa-799015de336d/air-max-excee-womens-shoe-jKsgMj.png"
                    }
                  />
                }
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__nYYlJ)}
                slot2={
                  <React.Fragment>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__ze78G)}
                    >
                      <Tag
                        children22={"winter 2020"}
                        className={classNames("__wab_instance", sty.tag__seGgg)}
                      />

                      <Tag
                        children22={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box___8M0F3
                            )}
                          >
                            {"sale"}
                          </div>
                        }
                        className={classNames(
                          "__wab_instance",
                          sty.tag___4WfUw
                        )}
                      />
                    </p.Stack>

                    <h3
                      className={classNames(
                        defaultcss.h3,
                        defaultcss.__wab_text,
                        sty.h3__k1Kpp
                      )}
                    >
                      {"Summer special sneakers"}
                    </h3>

                    <Price
                      className={classNames("__wab_instance", sty.price__u1Hnk)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box___2Tf4M
                        )}
                      >
                        {"199"}
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__h9FZx
                        )}
                      >
                        {"99"}
                      </div>
                    </Price>
                  </React.Fragment>
                }
                slot3={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__vqbU)}
                    role={"img"}
                    src={
                      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-de6bc64d-3bbe-434a-9073-751c3b5edd15/air-max-bella-tr-3-womens-training-shoe-fl5g5G.png"
                    }
                  />
                }
              />

              <ProductCard
                className={classNames(
                  "__wab_instance",
                  sty.productCard___2UpHi
                )}
                slot2={
                  <React.Fragment>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__axxSf)}
                    >
                      <Tag
                        children22={"winter 2020"}
                        className={classNames("__wab_instance", sty.tag__apvDj)}
                      />

                      <Tag
                        children22={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__xzaw
                            )}
                          >
                            {"sale"}
                          </div>
                        }
                        className={classNames(
                          "__wab_instance",
                          sty.tag___6ReR4
                        )}
                      />
                    </p.Stack>

                    <h3
                      className={classNames(
                        defaultcss.h3,
                        defaultcss.__wab_text,
                        sty.h3__hZ8BJ
                      )}
                    >
                      {"Summer special sneakers"}
                    </h3>

                    <Price
                      className={classNames("__wab_instance", sty.price__baa9M)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__bznP
                        )}
                      >
                        {"199"}
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__km47Q
                        )}
                      >
                        {"99"}
                      </div>
                    </Price>
                  </React.Fragment>
                }
                slot3={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__fsQMi)}
                    role={"img"}
                    src={
                      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/a07d08d2-165f-4359-bf85-611952ff719e/quest-3-womens-running-shoe-BBjpVm.png"
                    }
                  />
                }
              />
            </p.Stack>
          </p.Stack>

          <p.Stack
            as={"section"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.section__kb6Uv)}
          >
            <div className={classNames(defaultcss.all, sty.box__b5ST)}>
              <h3
                className={classNames(
                  defaultcss.h3,
                  defaultcss.__wab_text,
                  sty.h3__xh7U4
                )}
              >
                {"Flash sale!"}
              </h3>

              <Button
                className={classNames("__wab_instance", sty.button___0FQNl)}
                slot={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__pg0Qt
                    )}
                  >
                    {"Browse all ->"}
                  </div>
                }
              />
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__lIUys)}
            >
              <ProductCard
                className={classNames("__wab_instance", sty.productCard__n5Mrz)}
                horizontal={"horizontal"}
                slot2={
                  <React.Fragment>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__qGci)}
                    >
                      {false ? (
                        <Tag
                          className={classNames(
                            "__wab_instance",
                            sty.tag___1JZpz
                          )}
                        />
                      ) : null}

                      <Tag
                        children22={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__nsToL
                            )}
                          >
                            {"sale"}
                          </div>
                        }
                        className={classNames("__wab_instance", sty.tag__zJcQ)}
                      />
                    </p.Stack>

                    <h3
                      className={classNames(
                        defaultcss.h3,
                        defaultcss.__wab_text,
                        sty.h3__oPuGa
                      )}
                    >
                      {"Stay and Fight"}
                    </h3>

                    <h3
                      className={classNames(
                        defaultcss.h3,
                        defaultcss.__wab_text,
                        sty.h3__m5S5R
                      )}
                    >
                      {"by Maeline Ffitch"}
                    </h3>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__y3L12)}
                    >
                      <Price>
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__wG9Jh
                          )}
                        >
                          {"20"}
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__vs190
                          )}
                        >
                          {".00"}
                        </div>
                      </Price>

                      <Price
                        slot={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__dae98
                            )}
                          >
                            {"$"}
                          </div>
                        }
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__eiZ5R
                          )}
                        >
                          {"24"}
                        </div>

                        {false ? (
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__yE7NU
                            )}
                          >
                            {".00"}
                          </div>
                        ) : null}
                      </Price>
                    </p.Stack>
                  </React.Fragment>
                }
                slot3={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__oWqrg)}
                    role={"img"}
                    src={
                      "https://images-na.ssl-images-amazon.com/images/I/71PL7BiZ5NL.jpg"
                    }
                  />
                }
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__t1Zwz)}
                horizontal={"horizontal"}
                slot2={
                  <React.Fragment>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__d5FwP)}
                    >
                      {false ? (
                        <Tag
                          className={classNames(
                            "__wab_instance",
                            sty.tag__sX8Gu
                          )}
                        />
                      ) : null}

                      <Tag
                        children22={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__yuZdd
                            )}
                          >
                            {"sale"}
                          </div>
                        }
                        className={classNames("__wab_instance", sty.tag__tVo5F)}
                      />
                    </p.Stack>

                    <h3
                      className={classNames(
                        defaultcss.h3,
                        defaultcss.__wab_text,
                        sty.h3__dbeA
                      )}
                    >
                      {"Picnic Comma Lightning"}
                    </h3>

                    <h3
                      className={classNames(
                        defaultcss.h3,
                        defaultcss.__wab_text,
                        sty.h3__ijTxX
                      )}
                    >
                      {"by Laurence Scott"}
                    </h3>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box___8FaKn)}
                    >
                      <Price>
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__ui8Ah
                          )}
                        >
                          {"22"}
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___5JgdS
                          )}
                        >
                          {".00"}
                        </div>
                      </Price>
                    </p.Stack>
                  </React.Fragment>
                }
                slot3={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__rw87S)}
                    role={"img"}
                    src={
                      "https://images-na.ssl-images-amazon.com/images/I/61Vc+xM23GL.jpg"
                    }
                  />
                }
              />

              <ProductCard
                className={classNames("__wab_instance", sty.productCard__jtJuD)}
                horizontal={"horizontal"}
                slot2={
                  <React.Fragment>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__mvVuW)}
                    >
                      {false ? (
                        <Tag
                          className={classNames(
                            "__wab_instance",
                            sty.tag__a1Zdv
                          )}
                        />
                      ) : null}

                      <Tag
                        children22={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__kbJas
                            )}
                          >
                            {"sale"}
                          </div>
                        }
                        className={classNames("__wab_instance", sty.tag__ldwKi)}
                      />
                    </p.Stack>

                    <h3
                      className={classNames(
                        defaultcss.h3,
                        defaultcss.__wab_text,
                        sty.h3__cGImP
                      )}
                    >
                      {"A Tale for the Time Being"}
                    </h3>

                    <h3
                      className={classNames(
                        defaultcss.h3,
                        defaultcss.__wab_text,
                        sty.h3__y8SDn
                      )}
                    >
                      {"by Ruth Ozeki"}
                    </h3>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box___4XTac)}
                    >
                      <Price>
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__vcXi8
                          )}
                        >
                          {"22"}
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__v5N6F
                          )}
                        >
                          {".00"}
                        </div>
                      </Price>
                    </p.Stack>
                  </React.Fragment>
                }
                slot3={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___5XSwT)}
                    role={"img"}
                    src={
                      "https://www.abebooks.com/blog/wp-content/uploads/2016/08/10.jpg"
                    }
                  />
                }
              />
            </p.Stack>
          </p.Stack>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "shopBanners"],
  shopBanners: ["shopBanners"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicShop__ArgProps,
      internalVariantPropNames: PlasmicShop__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicShop__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicShop";
  } else {
    func.displayName = `PlasmicShop.${nodeName}`;
  }
  return func;
}

export const PlasmicShop = Object.assign(
  // Top-level PlasmicShop renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    shopBanners: makeNodeComponent("shopBanners"),
    // Metadata about props expected for PlasmicShop
    internalVariantProps: PlasmicShop__VariantProps,
    internalArgProps: PlasmicShop__ArgProps
  }
);

export default PlasmicShop;
/* prettier-ignore-end */
