// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3SwC2F4BeXucfS9cpFbd24
// Component: 1HNoA3RGWknK
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import HeroSection4 from "../../HeroSection4"; // plasmic-import: sf7ZQXAWpm2/component
import HeroSection1 from "../../HeroSection1"; // plasmic-import: Rjx0SznpO8x/component
import HeroSection2 from "../../HeroSection2"; // plasmic-import: 3XNBWGhrQYp/component
import HeroSection3 from "../../HeroSection3"; // plasmic-import: 6sL1mv-UpYN/component
import ValuesSection1 from "../../ValuesSection1"; // plasmic-import: sZ2hF1JP9pZ/component
import Valueprop from "../../Valueprop"; // plasmic-import: YnVQB3eyyN/component
import ValuesSection2Light from "../../ValuesSection2Light"; // plasmic-import: y61Y3cT5trU/component
import ValuesSection2Dark from "../../ValuesSection2Dark"; // plasmic-import: e-zwD-1wQRG/component
import ValuesSection3 from "../../ValuesSection3"; // plasmic-import: MA4bVcmaSsw/component
import ValuesSection4 from "../../ValuesSection4"; // plasmic-import: XBw1Lgr7lQD/component
import ValuesSection5 from "../../ValuesSection5"; // plasmic-import: 18w6Cg8-8R8/component
import CallToActionSection1 from "../../CallToActionSection1"; // plasmic-import: qZnnGE7HkYG/component
import CallToActionSection2 from "../../CallToActionSection2"; // plasmic-import: 2GvVfBT0STM/component
import CallToActionSection3 from "../../CallToActionSection3"; // plasmic-import: DRp_-yK5MNO/component
import PricingSection1 from "../../PricingSection1"; // plasmic-import: i6d1wKllYf9/component
import PricingSection2 from "../../PricingSection2"; // plasmic-import: imX9BlF4Uj8/component
import PricingSection3 from "../../PricingSection3"; // plasmic-import: 2eOBL4VENE9/component
import LogoCloudSection1 from "../../LogoCloudSection1"; // plasmic-import: _J0GKW5UfD/component
import LogoCloudSection2 from "../../LogoCloudSection2"; // plasmic-import: IaLiG14Rft/component
import TestimonialsSection1 from "../../TestimonialsSection1"; // plasmic-import: CkgoUikSrtH/component
import Testimonial from "../../Testimonial"; // plasmic-import: 1MFPRU1oT6/component
import FooterSection1 from "../../FooterSection1"; // plasmic-import: 68MguUIjb_J/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: K7Rqgqmh9OYf/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_kit.module.css"; // plasmic-import: 3SwC2F4BeXucfS9cpFbd24/projectcss
import * as sty from "./PlasmicHome.module.css"; // plasmic-import: 1HNoA3RGWknK/css
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: h9S1yezhrN/icon
import Icon21Icon from "./icons/PlasmicIcon__Icon21"; // plasmic-import: 0OrmAo3X9i/icon
import Icon18Icon from "./icons/PlasmicIcon__Icon18"; // plasmic-import: fhx-oSTxAr/icon
import Icon22Icon from "./icons/PlasmicIcon__Icon22"; // plasmic-import: VOPzjHk6_f/icon
import Icon23Icon from "./icons/PlasmicIcon__Icon23"; // plasmic-import: M8z71GurjA/icon

export const PlasmicHome__VariantProps = new Array();

export const PlasmicHome__ArgProps = new Array();

function PlasmicHome__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <HeroSection4
            data-plasmic-name={"heroSection4"}
            data-plasmic-override={overrides.heroSection4}
            className={classNames("__wab_instance", sty.heroSection4)}
          />

          <HeroSection1
            data-plasmic-name={"heroSection1"}
            data-plasmic-override={overrides.heroSection1}
            className={classNames("__wab_instance", sty.heroSection1)}
          />

          <HeroSection2
            data-plasmic-name={"heroSection2"}
            data-plasmic-override={overrides.heroSection2}
            className={classNames("__wab_instance", sty.heroSection2)}
          />

          <HeroSection3
            data-plasmic-name={"heroSection3"}
            data-plasmic-override={overrides.heroSection3}
            className={classNames("__wab_instance", sty.heroSection3)}
          />

          <ValuesSection1
            data-plasmic-name={"valuesSection1"}
            data-plasmic-override={overrides.valuesSection1}
            className={classNames("__wab_instance", sty.valuesSection1)}
          />

          <ValuesSection2Light
            data-plasmic-name={"valuesSection2Light"}
            data-plasmic-override={overrides.valuesSection2Light}
            className={classNames("__wab_instance", sty.valuesSection2Light)}
          />

          <ValuesSection2Dark
            data-plasmic-name={"valuesSection2Dark"}
            data-plasmic-override={overrides.valuesSection2Dark}
            className={classNames("__wab_instance", sty.valuesSection2Dark)}
          />

          <ValuesSection3
            data-plasmic-name={"valuesSection3"}
            data-plasmic-override={overrides.valuesSection3}
            className={classNames("__wab_instance", sty.valuesSection3)}
            foreground={
              <React.Fragment>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__lQsui)}
                >
                  <div className={classNames(defaultcss.all, sty.box__vv2Yc)}>
                    <h2
                      className={classNames(
                        defaultcss.h2,
                        defaultcss.__wab_text,
                        sty.h2__rHyQw
                      )}
                    >
                      {"Proposing values"}
                    </h2>
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__mc8E9
                    )}
                  >
                    {
                      "Consectetur a adipiscing sagittis sed proin libero himenaeos ornare adipiscing suscipit leo vestibulum facilisi consequat nisi nisi adipiscing habitant facilisis suspendisse hac integer eget quam facilisis sem placerat fames."
                    }
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__buLhh)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box___3DdoM)}
                  >
                    <Valueprop
                      className={classNames(
                        "__wab_instance",
                        sty.valueprop__xN3Wk
                      )}
                      flat={"flat"}
                      slot={
                        "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                      }
                      slot2={
                        <Icon14Icon
                          className={classNames(
                            defaultcss.all,
                            sty.svg___4Yfxk
                          )}
                          role={"img"}
                        />
                      }
                    >
                      {"Powerful"}
                    </Valueprop>

                    <Valueprop
                      className={classNames(
                        "__wab_instance",
                        sty.valueprop__kkR3O
                      )}
                      flat={"flat"}
                      slot={
                        "Consequat scelerisque a eros taciti nisl a sodales."
                      }
                      slot2={
                        <Icon14Icon
                          className={classNames(
                            defaultcss.all,
                            sty.svg___6PGoI
                          )}
                          role={"img"}
                        />
                      }
                    >
                      {"Faster"}
                    </Valueprop>

                    <Valueprop
                      className={classNames(
                        "__wab_instance",
                        sty.valueprop__xySyl
                      )}
                      flat={"flat"}
                      slot={"At ut condimentum amet adipiscing ac diam a."}
                      slot2={
                        <Icon14Icon
                          className={classNames(defaultcss.all, sty.svg__ouAsh)}
                          role={"img"}
                        />
                      }
                    >
                      {"Best and brightest"}
                    </Valueprop>

                    <Valueprop
                      className={classNames(
                        "__wab_instance",
                        sty.valueprop__fvZl4
                      )}
                      flat={"flat"}
                      slot={
                        "Donec purus nec vestibulum volutpat vivamus vulputate suspendisse."
                      }
                      slot2={
                        <Icon14Icon
                          className={classNames(
                            defaultcss.all,
                            sty.svg___1SuP5
                          )}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__lZzTm
                        )}
                      >
                        {"Dynamic range"}
                      </div>
                    </Valueprop>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__d8Cox)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__t2Eky)}
                  >
                    <Valueprop
                      className={classNames(
                        "__wab_instance",
                        sty.valueprop__ifSm8
                      )}
                      flat={"flat"}
                      slot={
                        "Commodo pretium himenaeos nisi potenti ad in ante."
                      }
                      slot2={
                        <Icon14Icon
                          className={classNames(defaultcss.all, sty.svg__zEyo)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__wpPjG
                        )}
                      >
                        {"Portable"}
                      </div>
                    </Valueprop>

                    <Valueprop
                      className={classNames(
                        "__wab_instance",
                        sty.valueprop__qVtZ7
                      )}
                      flat={"flat"}
                      slot={"Magna ullamcorper ut arcu nisi a per facilisis."}
                      slot2={
                        <Icon14Icon
                          className={classNames(defaultcss.all, sty.svg__x6O12)}
                          role={"img"}
                        />
                      }
                    >
                      {"Production-ready"}
                    </Valueprop>

                    <Valueprop
                      className={classNames(
                        "__wab_instance",
                        sty.valueprop__hjSTw
                      )}
                      flat={"flat"}
                      slot={
                        "Ac lobortis praesent sagittis dictumst fermentum vestibulum nunc."
                      }
                      slot2={
                        <Icon14Icon
                          className={classNames(defaultcss.all, sty.svg__pYsRg)}
                          role={"img"}
                        />
                      }
                    >
                      {"Magical"}
                    </Valueprop>

                    <Valueprop
                      className={classNames(
                        "__wab_instance",
                        sty.valueprop__rKPnk
                      )}
                      flat={"flat"}
                      slot={
                        "A parturient mi suspendisse nisl inceptos nullam a."
                      }
                      slot2={
                        <Icon14Icon
                          className={classNames(defaultcss.all, sty.svg__pke)}
                          role={"img"}
                        />
                      }
                    >
                      {"Accessible"}
                    </Valueprop>
                  </p.Stack>
                </p.Stack>
              </React.Fragment>
            }
          />

          <ValuesSection4
            data-plasmic-name={"valuesSection4"}
            data-plasmic-override={overrides.valuesSection4}
            className={classNames("__wab_instance", sty.valuesSection4)}
            foreground={
              <React.Fragment>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__gAz70)}
                >
                  <div className={classNames(defaultcss.all, sty.box__qCbwR)}>
                    <h2
                      className={classNames(
                        defaultcss.h2,
                        defaultcss.__wab_text,
                        sty.h2__liLol
                      )}
                    >
                      {"Next-level"}
                    </h2>
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__wxFhp
                    )}
                  >
                    {"Dui urna enim a tempus commodo adipiscing ullamcorper."}
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__acjk)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__xzjXl)}
                  >
                    <Valueprop
                      className={classNames(
                        "__wab_instance",
                        sty.valueprop__dtQsy
                      )}
                      dark={"dark"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__zIaQw
                          )}
                        >
                          {
                            "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                          }
                        </div>
                      }
                      slot2={
                        <Icon21Icon
                          className={classNames(defaultcss.all, sty.svg__z9LMk)}
                          role={"img"}
                        />
                      }
                      vertical={"vertical"}
                    >
                      {"Harder"}
                    </Valueprop>

                    <Valueprop
                      className={classNames(
                        "__wab_instance",
                        sty.valueprop__qKYpW
                      )}
                      dark={"dark"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___5LDs
                          )}
                        >
                          {
                            "Consequat scelerisque a eros taciti nisl a sodales."
                          }
                        </div>
                      }
                      slot2={
                        <Icon18Icon
                          className={classNames(defaultcss.all, sty.svg__eb5Gu)}
                          role={"img"}
                        />
                      }
                      vertical={"vertical"}
                    >
                      {"Better"}
                    </Valueprop>

                    <Valueprop
                      className={classNames(
                        "__wab_instance",
                        sty.valueprop__rhAIs
                      )}
                      dark={"dark"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__b04Pc
                          )}
                        >
                          {
                            "Varius ad malesuada ullamcorper cursus scelerisque a a."
                          }
                        </div>
                      }
                      slot2={
                        <Icon22Icon
                          className={classNames(defaultcss.all, sty.svg__kB9Cs)}
                          role={"img"}
                        />
                      }
                      vertical={"vertical"}
                    >
                      {"Faster"}
                    </Valueprop>

                    <Valueprop
                      className={classNames(
                        "__wab_instance",
                        sty.valueprop__sP7Hk
                      )}
                      dark={"dark"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__joU6F
                          )}
                        >
                          {
                            "Ut eu nam nostra taciti congue adipiscing curabitur."
                          }
                        </div>
                      }
                      slot2={
                        <Icon23Icon
                          className={classNames(defaultcss.all, sty.svg__kkuYy)}
                          role={"img"}
                        />
                      }
                      vertical={"vertical"}
                    >
                      {"Stronger"}
                    </Valueprop>
                  </p.Stack>
                </p.Stack>
              </React.Fragment>
            }
          />

          <ValuesSection5
            data-plasmic-name={"valuesSection5"}
            data-plasmic-override={overrides.valuesSection5}
            className={classNames("__wab_instance", sty.valuesSection5)}
          />

          <CallToActionSection1
            data-plasmic-name={"callToActionSection1"}
            data-plasmic-override={overrides.callToActionSection1}
            className={classNames("__wab_instance", sty.callToActionSection1)}
          />

          <CallToActionSection2
            data-plasmic-name={"callToActionSection2"}
            data-plasmic-override={overrides.callToActionSection2}
            className={classNames("__wab_instance", sty.callToActionSection2)}
          />

          <CallToActionSection3
            data-plasmic-name={"callToActionSection3"}
            data-plasmic-override={overrides.callToActionSection3}
            className={classNames("__wab_instance", sty.callToActionSection3)}
          />

          <PricingSection1
            data-plasmic-name={"pricingSection1"}
            data-plasmic-override={overrides.pricingSection1}
            className={classNames("__wab_instance", sty.pricingSection1)}
          />

          <PricingSection2
            data-plasmic-name={"pricingSection2"}
            data-plasmic-override={overrides.pricingSection2}
            className={classNames("__wab_instance", sty.pricingSection2)}
          />

          <PricingSection3
            data-plasmic-name={"pricingSection3"}
            data-plasmic-override={overrides.pricingSection3}
            className={classNames("__wab_instance", sty.pricingSection3)}
          />

          <LogoCloudSection1
            data-plasmic-name={"logoCloudSection1"}
            data-plasmic-override={overrides.logoCloudSection1}
            className={classNames("__wab_instance", sty.logoCloudSection1)}
          />

          <LogoCloudSection2
            data-plasmic-name={"logoCloudSection2"}
            data-plasmic-override={overrides.logoCloudSection2}
            className={classNames("__wab_instance", sty.logoCloudSection2)}
          />

          <TestimonialsSection1
            data-plasmic-name={"testimonialsSection1"}
            data-plasmic-override={overrides.testimonialsSection1}
            className={classNames("__wab_instance", sty.testimonialsSection1)}
          >
            <Testimonial
              className={classNames("__wab_instance", sty.testimonial__gPrut)}
              slot={
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__faj4)}
                  role={"img"}
                  src={
                    "https://www.caa.com/sites/default/files/styles/headshot_500x500/public/speaker-headshots/Morgan_CAAspeakers_Heashot_Web.jpg?itok=WCOhQ1Hj"
                  }
                />
              }
            />

            <Testimonial
              className={classNames("__wab_instance", sty.testimonial__qpy4Y)}
              slot={
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__ixu3L)}
                  role={"img"}
                  src={
                    "https://tv-fanatic-res.cloudinary.com/iu/s--eXCbHIe1--/t_teaser_wide/cs_srgb,f_auto,fl_strip_profile.lossy,q_auto:420/v1371156342/elaine-benes-picture.png"
                  }
                />
              }
              slot2={"Elaine Benes"}
              slot3={"Editor, Pendant Publishing"}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__h1YlC
                )}
              >
                {'"Vestibulum lacinia varius habitant dis aenean.'}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__u6FzI
                )}
              >
                {
                  'A parturient non ultricies a parturient leo a nascetur at consectetur turpis praesent mus ornare nulla posuere vel parturient."'
                }
              </div>
            </Testimonial>

            <Testimonial
              className={classNames("__wab_instance", sty.testimonial__m6Dp0)}
              slot={
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__en9Rl)}
                  role={"img"}
                  src={
                    "https://i.pinimg.com/originals/87/d7/7d/87d77d68368fe5361d535b51cc5af09a.jpg"
                  }
                />
              }
              slot2={
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__kyLvb
                  )}
                >
                  {"Woody Boyd"}
                </div>
              }
              slot3={
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__nGghl
                  )}
                >
                  {"Assistant Bartender, Cheers"}
                </div>
              }
            >
              {
                '"A ullamcorper etiam gravida a non maecenas ac parturient lectus vestibulum nam."'
              }
            </Testimonial>

            <Testimonial
              className={classNames("__wab_instance", sty.testimonial__csmyP)}
              slot={
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__is3W6)}
                  role={"img"}
                  src={
                    "https://a1cf74336522e87f135f-2f21ace9a6cf0052456644b80fa06d4f.ssl.cf2.rackcdn.com/images/characters_opt/p-fresh-randall-park.jpg"
                  }
                />
              }
              slot2={"Louis Huang"}
              slot3={
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__llLS
                  )}
                >
                  {"Restaurant Owner, Cattleman's Ranch"}
                </div>
              }
            >
              {
                '"Purus dis a primis rhoncus blandit velit suspendisse porta at ullamcorper suscipit a scelerisque sed pharetra facilisi vitae."'
              }
            </Testimonial>
          </TestimonialsSection1>

          <FooterSection1
            data-plasmic-name={"footerSection1"}
            data-plasmic-override={overrides.footerSection1}
            className={classNames("__wab_instance", sty.footerSection1)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "heroSection4",
    "heroSection1",
    "heroSection2",
    "heroSection3",
    "valuesSection1",
    "valuesSection2Light",
    "valuesSection2Dark",
    "valuesSection3",
    "valuesSection4",
    "valuesSection5",
    "callToActionSection1",
    "callToActionSection2",
    "callToActionSection3",
    "pricingSection1",
    "pricingSection2",
    "pricingSection3",
    "logoCloudSection1",
    "logoCloudSection2",
    "testimonialsSection1",
    "footerSection1"
  ],

  heroSection4: ["heroSection4"],
  heroSection1: ["heroSection1"],
  heroSection2: ["heroSection2"],
  heroSection3: ["heroSection3"],
  valuesSection1: ["valuesSection1"],
  valuesSection2Light: ["valuesSection2Light"],
  valuesSection2Dark: ["valuesSection2Dark"],
  valuesSection3: ["valuesSection3"],
  valuesSection4: ["valuesSection4"],
  valuesSection5: ["valuesSection5"],
  callToActionSection1: ["callToActionSection1"],
  callToActionSection2: ["callToActionSection2"],
  callToActionSection3: ["callToActionSection3"],
  pricingSection1: ["pricingSection1"],
  pricingSection2: ["pricingSection2"],
  pricingSection3: ["pricingSection3"],
  logoCloudSection1: ["logoCloudSection1"],
  logoCloudSection2: ["logoCloudSection2"],
  testimonialsSection1: ["testimonialsSection1"],
  footerSection1: ["footerSection1"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    heroSection4: makeNodeComponent("heroSection4"),
    heroSection1: makeNodeComponent("heroSection1"),
    heroSection2: makeNodeComponent("heroSection2"),
    heroSection3: makeNodeComponent("heroSection3"),
    valuesSection1: makeNodeComponent("valuesSection1"),
    valuesSection2Light: makeNodeComponent("valuesSection2Light"),
    valuesSection2Dark: makeNodeComponent("valuesSection2Dark"),
    valuesSection3: makeNodeComponent("valuesSection3"),
    valuesSection4: makeNodeComponent("valuesSection4"),
    valuesSection5: makeNodeComponent("valuesSection5"),
    callToActionSection1: makeNodeComponent("callToActionSection1"),
    callToActionSection2: makeNodeComponent("callToActionSection2"),
    callToActionSection3: makeNodeComponent("callToActionSection3"),
    pricingSection1: makeNodeComponent("pricingSection1"),
    pricingSection2: makeNodeComponent("pricingSection2"),
    pricingSection3: makeNodeComponent("pricingSection3"),
    logoCloudSection1: makeNodeComponent("logoCloudSection1"),
    logoCloudSection2: makeNodeComponent("logoCloudSection2"),
    testimonialsSection1: makeNodeComponent("testimonialsSection1"),
    footerSection1: makeNodeComponent("footerSection1"),
    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
