// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3SwC2F4BeXucfS9cpFbd24
// Component: i6d1wKllYf9
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: QaipWgLIw8/component
import Divider from "../../Divider"; // plasmic-import: 41plLt4nRZ/component
import Valueprop from "../../Valueprop"; // plasmic-import: YnVQB3eyyN/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: K7Rqgqmh9OYf/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_kit.module.css"; // plasmic-import: 3SwC2F4BeXucfS9cpFbd24/projectcss
import * as sty from "./PlasmicPricingSection1.module.css"; // plasmic-import: i6d1wKllYf9/css
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: h9S1yezhrN/icon

export const PlasmicPricingSection1__VariantProps = new Array();

export const PlasmicPricingSection1__ArgProps = new Array();

function PlasmicPricingSection1__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box__l7Een)}
      >
        <div className={classNames(defaultcss.all, sty.box__cb7Eb)}>
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__g6G6A
            )}
          >
            {"Pricing plans"}
          </div>
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.box__pivi1
          )}
        >
          {
            "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
          }
        </div>
      </p.Stack>

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box__lBqT9)}
      >
        <div className={classNames(defaultcss.all, sty.box__c8Ddd)}>
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box__bMm57)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__qUdIu)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__joLds
                )}
              >
                {"Starter"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__y4Y4D
                )}
              >
                {"All the basics"}
              </div>
            </p.Stack>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__v04Do
              )}
            >
              {"Free"}
            </div>

            <Button darkGray={"darkGray"} slot={"Get started"} />
          </p.Stack>

          <Divider
            className={classNames("__wab_instance", sty.divider__fvsUp)}
          />

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box__p1Ftj)}
          >
            <Valueprop
              className={classNames("__wab_instance", sty.valueprop__d8Gcz)}
              flatIcon={"flatIcon"}
              justDescription={"justDescription"}
              slot={
                "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
              }
              slot2={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__xkzaZ)}
                  role={"img"}
                />
              }
              slot22={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__xUqF)}
                  role={"img"}
                />
              }
            />

            <Valueprop
              className={classNames("__wab_instance", sty.valueprop__e2KqS)}
              flatIcon={"flatIcon"}
              justDescription={"justDescription"}
              slot={
                "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
              }
              slot2={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__bcY1O)}
                  role={"img"}
                />
              }
              slot22={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__w7Jzt)}
                  role={"img"}
                />
              }
            />
          </p.Stack>
        </div>

        <div className={classNames(defaultcss.all, sty.box___7G5Io)}>
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box__oOmiN)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__liNo5)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__kL0J
                )}
              >
                {"Pro"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box___4Im
                )}
              >
                {"Best deal"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__ix0N4)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__dgBu7
                )}
              >
                {"$8"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__j6VnQ
                )}
              >
                {"/mo"}
              </div>
            </p.Stack>

            <Button
              colors={"red"}
              slot={
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__o0Er
                  )}
                >
                  {"Purchase pro"}
                </div>
              }
            />
          </p.Stack>

          <Divider
            className={classNames("__wab_instance", sty.divider___4CrVx)}
          />

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box__gXsIv)}
          >
            <Valueprop
              className={classNames("__wab_instance", sty.valueprop__aNp5K)}
              flatIcon={"flatIcon"}
              justDescription={"justDescription"}
              slot={
                "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
              }
              slot2={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__n9IIy)}
                  role={"img"}
                />
              }
              slot22={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg___14Qkh)}
                  role={"img"}
                />
              }
            />

            <Valueprop
              className={classNames("__wab_instance", sty.valueprop__acPom)}
              flatIcon={"flatIcon"}
              justDescription={"justDescription"}
              slot={
                "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
              }
              slot2={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__nv8T)}
                  role={"img"}
                />
              }
              slot22={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__mGnCe)}
                  role={"img"}
                />
              }
            />

            <Valueprop
              className={classNames("__wab_instance", sty.valueprop__rhq8D)}
              flatIcon={"flatIcon"}
              justDescription={"justDescription"}
              slot={
                "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
              }
              slot2={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__pJ4Dq)}
                  role={"img"}
                />
              }
              slot22={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__sgL0E)}
                  role={"img"}
                />
              }
            />
          </p.Stack>
        </div>

        <div className={classNames(defaultcss.all, sty.box___0Qpv)}>
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box__gx093)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__xFpjv)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__b5E3I
                )}
              >
                {"Team"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__rCka
                )}
              >
                {"Level up"}
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__rp44)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__rYio
                )}
              >
                {"$16"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box___8Xbfw
                )}
              >
                {"/mo"}
              </div>
            </p.Stack>

            <Button colors={"green"} slot={"Get started"} />
          </p.Stack>

          <Divider
            className={classNames("__wab_instance", sty.divider__s1Ae)}
          />

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box__j9VEy)}
          >
            <Valueprop
              className={classNames("__wab_instance", sty.valueprop__nznyk)}
              flatIcon={"flatIcon"}
              justDescription={"justDescription"}
              slot={
                "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
              }
              slot2={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__nRghL)}
                  role={"img"}
                />
              }
              slot22={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__kyCvC)}
                  role={"img"}
                />
              }
            />

            <Valueprop
              className={classNames("__wab_instance", sty.valueprop__yKyn1)}
              flatIcon={"flatIcon"}
              justDescription={"justDescription"}
              slot={
                "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
              }
              slot2={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__arCh)}
                  role={"img"}
                />
              }
              slot22={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__yMVgp)}
                  role={"img"}
                />
              }
            />

            <Valueprop
              className={classNames("__wab_instance", sty.valueprop___72Rcs)}
              flatIcon={"flatIcon"}
              justDescription={"justDescription"}
              slot={
                "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
              }
              slot2={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__fxmM9)}
                  role={"img"}
                />
              }
              slot22={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__dRpxI)}
                  role={"img"}
                />
              }
            />

            <Valueprop
              className={classNames("__wab_instance", sty.valueprop__iwBTd)}
              flatIcon={"flatIcon"}
              justDescription={"justDescription"}
              slot={
                "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
              }
              slot2={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg___2GaF)}
                  role={"img"}
                />
              }
              slot22={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__jvjRj)}
                  role={"img"}
                />
              }
            />
          </p.Stack>
        </div>

        <div className={classNames(defaultcss.all, sty.box__mXdwy)}>
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box__seZc9)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__tdv8V)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__rg7Qm
                )}
              >
                {"Enterprise"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box___37Wmh
                )}
              >
                {"Fine-tune everything"}
              </div>
            </p.Stack>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__l2G11
              )}
            >
              {"Custom"}
            </div>

            <Button
              colors={"blue"}
              slot={
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__iLirT
                  )}
                >
                  {"Contact us"}
                </div>
              }
            />
          </p.Stack>

          <Divider
            className={classNames("__wab_instance", sty.divider__fd5Lt)}
          />

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box__mfym)}
          >
            <Valueprop
              className={classNames("__wab_instance", sty.valueprop__iPqO)}
              flatIcon={"flatIcon"}
              justDescription={"justDescription"}
              slot={
                "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
              }
              slot2={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__lwwDn)}
                  role={"img"}
                />
              }
              slot22={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__frfXq)}
                  role={"img"}
                />
              }
            />

            <Valueprop
              className={classNames("__wab_instance", sty.valueprop__bffia)}
              flatIcon={"flatIcon"}
              justDescription={"justDescription"}
              slot={
                "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
              }
              slot2={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__vO42Z)}
                  role={"img"}
                />
              }
              slot22={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__lVxJ1)}
                  role={"img"}
                />
              }
            />

            <Valueprop
              className={classNames("__wab_instance", sty.valueprop__nRRg)}
              flatIcon={"flatIcon"}
              justDescription={"justDescription"}
              slot={
                "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
              }
              slot2={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__xMNB)}
                  role={"img"}
                />
              }
              slot22={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__stQw)}
                  role={"img"}
                />
              }
            />

            <Valueprop
              className={classNames("__wab_instance", sty.valueprop__gbCsj)}
              flatIcon={"flatIcon"}
              justDescription={"justDescription"}
              slot={
                "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
              }
              slot2={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__sMGwf)}
                  role={"img"}
                />
              }
              slot22={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__wwZou)}
                  role={"img"}
                />
              }
            />

            <Valueprop
              className={classNames("__wab_instance", sty.valueprop__kiPk)}
              flatIcon={"flatIcon"}
              justDescription={"justDescription"}
              slot={
                "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
              }
              slot2={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__sb4Hp)}
                  role={"img"}
                />
              }
              slot22={
                <Icon14Icon
                  className={classNames(defaultcss.all, sty.svg__bQyiH)}
                  role={"img"}
                />
              }
            />
          </p.Stack>
        </div>
      </p.Stack>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPricingSection1__ArgProps,
      internalVariantPropNames: PlasmicPricingSection1__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicPricingSection1__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPricingSection1";
  } else {
    func.displayName = `PlasmicPricingSection1.${nodeName}`;
  }
  return func;
}

export const PlasmicPricingSection1 = Object.assign(
  // Top-level PlasmicPricingSection1 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicPricingSection1
    internalVariantProps: PlasmicPricingSection1__VariantProps,
    internalArgProps: PlasmicPricingSection1__ArgProps
  }
);

export default PlasmicPricingSection1;
/* prettier-ignore-end */
