// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3SwC2F4BeXucfS9cpFbd24
// Component: 68MguUIjb_J
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Logo from "../../Logo"; // plasmic-import: kEOdDr29tw/component
import Button from "../../Button"; // plasmic-import: QaipWgLIw8/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: K7Rqgqmh9OYf/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_kit.module.css"; // plasmic-import: 3SwC2F4BeXucfS9cpFbd24/projectcss
import * as sty from "./PlasmicFooterSection1.module.css"; // plasmic-import: 68MguUIjb_J/css
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: o5ppeaks74/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: dIWqYvwQI/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: 2Gh5liL0tt/icon

export const PlasmicFooterSection1__VariantProps = new Array();

export const PlasmicFooterSection1__ArgProps = new Array("children");

function PlasmicFooterSection1__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__g0Kj3)}
              >
                <Logo _50Opaque={"_50Opaque"} />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__uh0Lt)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__lQo7L
                    )}
                  >
                    {"Connect with us"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__ll0Gc)}
                  >
                    <Icon3Icon
                      className={classNames(defaultcss.all, sty.svg__bPllY)}
                      role={"img"}
                    />

                    <Icon2Icon
                      className={classNames(defaultcss.all, sty.svg__h1Ie)}
                      role={"img"}
                    />

                    <Icon28Icon
                      className={classNames(defaultcss.all, sty.svg__atkvE)}
                      role={"img"}
                    />
                  </p.Stack>
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__wxr1V)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__t7ZR3
                  )}
                >
                  {"Product"}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__viJfR)}
                  flat={"flat"}
                  linkLabel={"linkLabel"}
                  slot={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__o77RP
                      )}
                    >
                      {"Pricing"}
                    </div>
                  }
                />

                <Button
                  className={classNames("__wab_instance", sty.button__craH2)}
                  flat={"flat"}
                  linkLabel={"linkLabel"}
                  slot={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box___83LKt
                      )}
                    >
                      {"Log in"}
                    </div>
                  }
                />

                <Button
                  className={classNames("__wab_instance", sty.button___6Tkoq)}
                  flat={"flat"}
                  linkLabel={"linkLabel"}
                  slot={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__gfIkb
                      )}
                    >
                      {"Integrations"}
                    </div>
                  }
                />

                <Button
                  className={classNames("__wab_instance", sty.button__bpOP)}
                  flat={"flat"}
                  linkLabel={"linkLabel"}
                  slot={
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__bnxwj
                      )}
                    >
                      {"Insights"}
                    </div>
                  }
                />
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__soUbB)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__t3FUp
                  )}
                >
                  {"Support"}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__lLz7A)}
                  flat={"flat"}
                  linkLabel={"linkLabel"}
                  slot={"Documentation"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button___5TsGd)}
                  flat={"flat"}
                  linkLabel={"linkLabel"}
                  slot={"FAQs"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__hOtvm)}
                  flat={"flat"}
                  linkLabel={"linkLabel"}
                  slot={"Status"}
                />
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__psqPv)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__xhlhB
                  )}
                >
                  {"Company"}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__oOspI)}
                  flat={"flat"}
                  linkLabel={"linkLabel"}
                  slot={"About"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__xheX)}
                  flat={"flat"}
                  linkLabel={"linkLabel"}
                  slot={"Contact us"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__hhNhw)}
                  flat={"flat"}
                  linkLabel={"linkLabel"}
                  slot={"Careers"}
                />

                <Button
                  className={classNames("__wab_instance", sty.button__xQvdD)}
                  flat={"flat"}
                  linkLabel={"linkLabel"}
                  slot={"Media"}
                />
              </p.Stack>
            </React.Fragment>
          ),

          value: args.children
        })}
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFooterSection1__ArgProps,
      internalVariantPropNames: PlasmicFooterSection1__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicFooterSection1__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooterSection1";
  } else {
    func.displayName = `PlasmicFooterSection1.${nodeName}`;
  }
  return func;
}

export const PlasmicFooterSection1 = Object.assign(
  // Top-level PlasmicFooterSection1 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    // Metadata about props expected for PlasmicFooterSection1
    internalVariantProps: PlasmicFooterSection1__VariantProps,
    internalArgProps: PlasmicFooterSection1__ArgProps
  }
);

export default PlasmicFooterSection1;
/* prettier-ignore-end */
