// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3SwC2F4BeXucfS9cpFbd24
// Component: 2eOBL4VENE9
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Divider from "../../Divider"; // plasmic-import: 41plLt4nRZ/component
import Valueprop from "../../Valueprop"; // plasmic-import: YnVQB3eyyN/component
import Button from "../../Button"; // plasmic-import: QaipWgLIw8/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_kit.module.css"; // plasmic-import: 3SwC2F4BeXucfS9cpFbd24/projectcss
import * as sty from "./PlasmicPricingSection3.module.css"; // plasmic-import: 2eOBL4VENE9/css
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: h9S1yezhrN/icon

export const PlasmicPricingSection3__VariantProps = new Array();

export const PlasmicPricingSection3__ArgProps = new Array("foreground");

function PlasmicPricingSection3__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(defaultcss.all, sty.box)}
      />

      <p.Stack
        as={"div"}
        data-plasmic-name={"foreground"}
        data-plasmic-override={overrides.foreground}
        hasGap={true}
        className={classNames(defaultcss.all, sty.foreground)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__yekIm)}
              >
                <div className={classNames(defaultcss.all, sty.box__hSZu)}>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__oqi2C
                    )}
                  >
                    {"Pricing plans"}
                  </div>
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__wueP
                  )}
                >
                  {
                    "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                  }
                </div>
              </p.Stack>

              <div className={classNames(defaultcss.all, sty.box__d7FOi)}>
                <div className={classNames(defaultcss.all, sty.box__h1Pb)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__w7ANr)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__znxy
                      )}
                    >
                      {"Starter"}
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box___6833T)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__b8PwM)}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___0Pdwo
                          )}
                        >
                          {"$"}
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__gaFr
                          )}
                        >
                          {"8"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__eg3Ty
                        )}
                      >
                        {"/month"}
                      </div>
                    </p.Stack>
                  </p.Stack>

                  <Divider
                    className={classNames("__wab_instance", sty.divider__t8LPm)}
                  />

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__d5UQ)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__vbBjC)}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__l8Yma
                        )}
                        flatIcon={"flatIcon"}
                        justDescription={"justDescription"}
                        slot={
                          "Vestibulum mollis odio dictum ultrices facilisis molestie vestibulum"
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__k0Wv
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__sO5Z
                            )}
                            role={"img"}
                          />
                        }
                      />

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__umpBc
                        )}
                        flatIcon={"flatIcon"}
                        justDescription={"justDescription"}
                        slot={"Mus consequat a justo"}
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__phAC
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___94UAb
                            )}
                            role={"img"}
                          />
                        }
                      />
                    </p.Stack>

                    <Button
                      colors={"white"}
                      extraSmallShadow={"extraSmallShadow"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__eVhX3
                          )}
                        >
                          {"Buy starter"}
                        </div>
                      }
                    />
                  </p.Stack>
                </div>

                <div className={classNames(defaultcss.all, sty.box__kwSbN)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__iwb8T)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__tlHbG
                      )}
                    >
                      {"Pro"}
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__riLkO)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__v8T8Z)}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__z8Xoa
                          )}
                        >
                          {"$"}
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___7OGiJ
                          )}
                        >
                          {"16"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__oS9RZ
                        )}
                      >
                        {"/month"}
                      </div>
                    </p.Stack>
                  </p.Stack>

                  <Divider
                    className={classNames("__wab_instance", sty.divider__uy4Dr)}
                  />

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__safAt)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__ox4Qe)}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__uPvYd
                        )}
                        flatIcon={"flatIcon"}
                        justDescription={"justDescription"}
                        slot={
                          "Ligula primis mollis sem dignissim semper lectus parturient"
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__th4Cd
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__gxIv4
                            )}
                            role={"img"}
                          />
                        }
                      />

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__kse6U
                        )}
                        flatIcon={"flatIcon"}
                        justDescription={"justDescription"}
                        slot={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__tbntS
                            )}
                          >
                            {"A curabitur dignissim pharetra porta suscipit"}
                          </div>
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__dcB82
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__bc3Ot
                            )}
                            role={"img"}
                          />
                        }
                      />

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__cnjfi
                        )}
                        flatIcon={"flatIcon"}
                        justDescription={"justDescription"}
                        slot={
                          "Condimentum diam a et sapien praesent potenti torquent a eros"
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___8ZgdB
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___4Ui6U
                            )}
                            role={"img"}
                          />
                        }
                      />

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__xsQf
                        )}
                        flatIcon={"flatIcon"}
                        justDescription={"justDescription"}
                        slot={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__hDr8I
                            )}
                          >
                            {"Conubia in hac eu elementum sodales"}
                          </div>
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__dSm7A
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__e8U0
                            )}
                            role={"img"}
                          />
                        }
                      />
                    </p.Stack>

                    <Button
                      colors={"green"}
                      extraSmallShadow={"extraSmallShadow"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__o9HfH
                          )}
                        >
                          {"Buy pro"}
                        </div>
                      }
                    />
                  </p.Stack>
                </div>

                <div className={classNames(defaultcss.all, sty.box__hZsbN)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__fZh2B)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__pboQa
                      )}
                    >
                      {"Team"}
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__gyg0R)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box___2QKik)}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__vsEo
                          )}
                        >
                          {"$"}
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__iNbDd
                          )}
                        >
                          {"10"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__tAc5X
                        )}
                      >
                        {"/member"}
                      </div>
                    </p.Stack>
                  </p.Stack>

                  <Divider
                    className={classNames("__wab_instance", sty.divider__yZ6Of)}
                  />

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__ePKzH)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box___55FXi)}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop___1Ilnq
                        )}
                        flatIcon={"flatIcon"}
                        justDescription={"justDescription"}
                        slot={"Ad nam curae a potenti platea"}
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___2ZcRt
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__fuoNj
                            )}
                            role={"img"}
                          />
                        }
                      />

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__n6Eg
                        )}
                        flatIcon={"flatIcon"}
                        justDescription={"justDescription"}
                        slot={
                          "A adipiscing scelerisque pretium consectetur sem"
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__zpkIl
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__kan8D
                            )}
                            role={"img"}
                          />
                        }
                      />
                    </p.Stack>

                    <Button
                      colors={"white"}
                      extraSmallShadow={"extraSmallShadow"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___0Cb0A
                          )}
                        >
                          {"Buy team"}
                        </div>
                      }
                    />
                  </p.Stack>
                </div>
              </div>
            </React.Fragment>
          ),

          value: args.foreground
        })}
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "box", "foreground"],
  box: ["box"],
  foreground: ["foreground"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPricingSection3__ArgProps,
      internalVariantPropNames: PlasmicPricingSection3__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicPricingSection3__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPricingSection3";
  } else {
    func.displayName = `PlasmicPricingSection3.${nodeName}`;
  }
  return func;
}

export const PlasmicPricingSection3 = Object.assign(
  // Top-level PlasmicPricingSection3 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    foreground: makeNodeComponent("foreground"),
    // Metadata about props expected for PlasmicPricingSection3
    internalVariantProps: PlasmicPricingSection3__VariantProps,
    internalArgProps: PlasmicPricingSection3__ArgProps
  }
);

export default PlasmicPricingSection3;
/* prettier-ignore-end */
